/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "SBFScheduler.h"

@interface _SBFImmediateScheduler : NSObject <SBFScheduler>
{
}

- (id)afterDelay:(double)arg1 performBlock:(id)arg2;
- (id)performCancelableBlock:(id)arg1;
- (id)performBlock:(id)arg1;

@end

