/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "SBFObserver.h"

@interface _SBFBlockObserver : NSObject <SBFObserver>
{
    id _resultBlock;
    id _completionBlock;
    id _failureBlock;
}

- (void)observerDidFailWithError:(id)arg1;
- (void)observerDidComplete;
- (void)observerDidReceiveResult:(id)arg1;
- (void)dealloc;
- (id)initWithResultBlock:(id)arg1 completionBlock:(void)arg2 failureBlock:(id)arg3;

@end

