/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <SpringBoardFoundation/SBFObservable.h>

@interface _SBFBlockObservable : SBFObservable
{
    id _block;
}

- (id)subscribe:(id)arg1;
- (void)dealloc;
- (id)initWithBlock:(id)arg1;

@end

