/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol _UIBasicAnimationFactory <NSObject>
- (id)_basicAnimationForView:(id)arg1 withKeyPath:(id)arg2;

@optional
- (id)_timingFunctionForAnimationInView:(id)arg1 withKeyPath:(id)arg2;
- (id)_timingFunctionForAnimation;
@end

