/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBFLockScreenMetrics : NSObject
{
}

+ (struct UIEdgeInsets)slideToUnlockInsets;
+ (double)slideToUnlockOverlayMargin;
+ (double)slideToUnlockFontSize;
+ (double)cameraGrabberInset;
+ (double)dateViewBaselineY;

@end

