/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "SBFObservable.h"

@interface SBFObservable : NSObject <SBFObservable>
{
}

+ (id)forkJoin:(id)arg1;
+ (id)observableWithBlock:(id)arg1;
- (id)throttle:(double)arg1 onScheduler:(id)arg2;
- (id)subscribe:(id)arg1;
- (id)subscribeWithResultBlock:(id)arg1 completionBlock:(void)arg2 failureBlock:(id)arg3;
- (id)subscribeWithResultBlock:(id)arg1;
- (id)waitForResults:(id *)arg1;
- (id)map:(id)arg1;
- (id)generate:(id)arg1;
- (id)observeOn:(id)arg1;
- (id)subscribeOn:(id)arg1;

@end

