/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "SBFProceduralWallpaper.h"

@interface SBFProceduralWallpaper : UIView <SBFProceduralWallpaper>
{
}

+ (id)identifier;
- (id)view;
- (void)setAnimating:(_Bool)arg1;

// Remaining properties
@property(nonatomic) id <SBFProceduralWallpaperDelegate> delegate;

@end

