include theos/makefiles/common.mk

BUNDLE_NAME = NoSlowAnimations_FlipSwitch
NoSlowAnimations_FlipSwitch_FILES = Switch.x
NoSlowAnimations_FlipSwitch_FRAMEWORKS = UIKit
NoSlowAnimations_FlipSwitch_LIBRARIES = flipswitch
NoSlowAnimations_FlipSwitch_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk