/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "TPNumberPadDarkStyleButton.h"

#import "SBUIPasscodeNumberPadButton.h"

@interface SBPasscodeNumberPadButton : TPNumberPadDarkStyleButton <SBUIPasscodeNumberPadButton>
{
}

+ (double)_numberPadButtonOuterCircleDiameter;
+ (double)_numberPadButtonPaddingWidth;
+ (double)_numberPadButtonPaddingHeight;
+ (struct UIEdgeInsets)paddingOutsideRing;
+ (struct CGSize)defaultSize;
- (id)stringCharacter;
- (int)characterType;
- (id)initForCharacter:(unsigned int)arg1;

@end

