/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "_UIRemoteViewController.h"

#import "SBUIEmergencyCallHostInterface.h"

@interface SBUIEmergencyCallHostViewController : _UIRemoteViewController <SBUIEmergencyCallHostInterface>
{
}

+ (void)requestEmergencyCallControllerWithCompletion:(id)arg1;
+ (id)serviceViewControllerInterface;
+ (id)exportedInterface;
- (void)dismiss;

@end

