/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "SBWallpaperObserver.h"
#import "_SBFakeBlur.h"

@interface _SBAccessibilityTintView : UIView <_SBFakeBlur, SBWallpaperObserver>
{
    int _variant;
    id <_SBFakeBlurObserver> _observer;
}

@property(nonatomic) id <_SBFakeBlurObserver> observer; // @synthesize observer=_observer;
- (void)_updateBackgroundColor;
- (void)wallpaperLegibilitySettingsDidChange:(id)arg1 forVariant:(int)arg2;
- (void)wallpaperDidChangeForVariant:(int)arg1;
- (void)didMoveToSuperview;
- (void)didMoveToWindow;
- (int)effectiveStyle;
- (void)requestStyle:(int)arg1;
- (void)dealloc;
- (id)initWithVariant:(int)arg1;

@end

