/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class UIImage;

@interface _SBFakeBlurImage : NSObject
{
    UIImage *_image;
    int _style;
}

@property(readonly, nonatomic) int style; // @synthesize style=_style;
@property(readonly, nonatomic) UIImage *image; // @synthesize image=_image;
- (void)dealloc;
- (id)initWithImage:(id)arg1 style:(int)arg2;

@end

