/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "_SBFakeBlur.h"

@class SBFWallpaperView, UIImageView;

@interface _SBFakeBlurView : UIView <_SBFakeBlur>
{
    id <_SBFakeBlurObserver> _observer;
    int _requestedStyle;
    int _effectiveStyle;
    SBFWallpaperView *_wallpaperView;
    UIImageView *_imageView;
}

+ (id)_imageForStyle:(inout int *)arg1 withSource:(id)arg2;
@property(nonatomic) id <_SBFakeBlurObserver> observer; // @synthesize observer=_observer;
- (void)didMoveToWindow;
- (void)willMoveToWindow:(id)arg1;
- (void)layoutSubviews;
- (void)rotateToInterfaceOrientation:(int)arg1;
- (void)setBlurImage:(id)arg1;
- (id)blurImageWithSource:(id)arg1;
- (void)_setImage:(id)arg1 style:(int)arg2 notify:(BOOL)arg3;
- (void)_updateImageWithSource:(id)arg1 notifyObserver:(BOOL)arg2;
- (void)updateImageWithSource:(id)arg1;
- (void)reconfigureWithSource:(id)arg1;
@property(readonly, nonatomic) int variant;
- (void)dealloc;
- (id)initWithVariant:(int)arg1;
- (int)effectiveStyle;
- (void)requestStyle:(int)arg1;

@end

