/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "SBWallpaperObserver.h"
#import "_UISettingsKeyObserver.h"

@class NSHashTable, SBIconColorSettings;

@interface _SBIconWallpaperColorProvider : NSObject <_UISettingsKeyObserver, SBWallpaperObserver>
{
    SBIconColorSettings *_colorSettings;
    NSHashTable *_clients;
    struct CGColor *_blurColor;
    struct CGColor *_solidColor;
}

+ (BOOL)_supportsPhasedPatterns;
+ (id)sharedInstance;
- (void)_updateColors;
- (void)_updateBlurForClient:(id)arg1;
- (void)_updateClient:(id)arg1;
- (void)_updateAllClients;
- (void)wallpaperGeometryDidChangeForVariant:(int)arg1;
- (void)wallpaperLegibilitySettingsDidChange:(id)arg1 forVariant:(int)arg2;
- (void)wallpaperDidChangeForVariant:(int)arg1;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)updateColorForClientBoundsChange:(id)arg1;
- (void)removeClient:(id)arg1;
- (void)addClient:(id)arg1;
- (void)dealloc;
- (id)init;

@end

