/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "_SBIconProgressTransition.h"

@interface _SBIconProgressFractionTransition : _SBIconProgressTransition
{
    float _targetFraction;
}

+ (id)newTransitionToFraction:(float)arg1;
- (BOOL)isCompleteWithView:(id)arg1;
- (void)_updateView:(id)arg1 forDisplayedFraction:(float)arg2;
- (void)completeTransitionAndUpdateView:(id)arg1;
- (void)updateView:(id)arg1 withElapsedTime:(double)arg2;
- (void)updateToFraction:(float)arg1;

@end

