/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "_SBIconProgressTransition.h"

@class CAMediaTimingFunction;

@interface _SBIconProgressStateTransition : _SBIconProgressTransition
{
    double _totalElapsedTime;
    double _duration;
    CAMediaTimingFunction *_timingFunction;
    int _fromState;
    int _toState;
    float _fraction;
}

+ (Class)_classForTransitionFromState:(int)arg1 toState:(int)arg2;
+ (id)newTransitionFromState:(int)arg1 toState:(int)arg2;
- (void)_updateView:(id)arg1;
- (BOOL)isCompleteWithView:(id)arg1;
- (void)completeTransitionAndUpdateView:(id)arg1;
- (void)updateView:(id)arg1 withElapsedTime:(double)arg2;
- (void)dealloc;
- (id)_initWithFromState:(int)arg1 toState:(int)arg2;

@end

