/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol _SBIconWallpaperColorClient <NSObject>
- (BOOL)isBlurring;
- (void)setBlurring:(BOOL)arg1;
- (void)setWallpaperColor:(struct CGColor *)arg1 phase:(struct CGSize)arg2;
- (BOOL)wantsBlur:(id)arg1;
- (struct CGRect)wallpaperRelativeBounds;
@end

