/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol MPUSystemMediaControlsDelegate <NSObject>

@optional
- (void)systemMediaControlsViewController:(id)arg1 didTapOnTrackInformationView:(id)arg2;
- (void)systemMediaControlsViewController:(id)arg1 didReceiveTapOnControlType:(int)arg2;
@end

