/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSArray.h"

@interface NSArray (SpringBoard)
- (id)sbf_map:(id)arg1;
- (void)sbf_each:(id)arg1;
- (id)sbf_filter:(id)arg1;
- (id)sbf_firstObjectPassingTest:(id)arg1;
@end

