/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol SBAlertManagerDelegate <NSObject>

@optional
- (id)alertManager:(id)arg1 newAlertWindowForLockAlerts:(BOOL)arg2;
- (BOOL)alertManager:(id)arg1 shouldDeactivateDismissedAlert:(id)arg2;
@end

