/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

#import "UIScrollViewDelegate.h"

@class NSMutableArray, SBAppSliderScrollView, SBStopScrollingGestureRecognizer, UITapGestureRecognizer;

@interface SBAppSliderScrollingViewController : UIViewController <UIScrollViewDelegate>
{
    NSMutableArray *_items;
    SBAppSliderScrollView *_scrollView;
    BOOL _dragMaster;
    BOOL _preventScroll;
    UITapGestureRecognizer *_tapGesture;
    SBStopScrollingGestureRecognizer *_stopScrollingGesture;
    int _layoutOrientation;
    id _scrollDoneBlock;
    id <SBAppSliderScrollingViewDelegate> _delegate;
}

@property(nonatomic) id <SBAppSliderScrollingViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)_fireAndCleanupScrollCompleteBlockIfNecessary;
- (void)_setContentOffset:(struct CGPoint)arg1 animated:(BOOL)arg2;
- (void)_enableScrolling;
- (void)_disableScrolling;
- (BOOL)_isIndexVisible:(unsigned int)arg1 withSidePadding:(float)arg2;
- (void)_updateVisiblePageViews;
- (void)_layout;
- (void)_layoutIndexContainer:(unsigned int)arg1;
- (void)_generateViewIndexIfNecessary:(unsigned int)arg1;
- (struct CGRect)_naturalScrollViewFrame;
- (struct CGPoint)_centerOfIndex:(unsigned int)arg1;
- (float)_distanceBetweenCenters;
- (void)_handleStopGesture:(id)arg1;
- (void)_handleTapGesture:(id)arg1;
- (void)removeIndex:(unsigned int)arg1 duration:(double)arg2;
- (void)reloadInOrientation:(int)arg1;
- (float)_halfWidth;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)loadView;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (BOOL)shouldAutomaticallyForwardRotationMethods;
- (float)preferredHeightForOrientation:(int)arg1;
- (void)switcherWasDismissed:(BOOL)arg1;
- (struct _NSRange)visibleItems;
- (BOOL)isScrolling;
- (BOOL)_isAnyScrollContainerScrolling;
- (id)pageViewForIndex:(unsigned int)arg1;
- (unsigned int)currentPage;
- (void)_setScrollingDoneBlock:(id)arg1;
- (BOOL)isIndexVisible:(unsigned int)arg1;
- (unsigned int)settledIndexForNormalizedOffset:(inout float *)arg1 andXVelocity:(float)arg2;
- (float)normalizedOffsetForOffset:(float)arg1 andXVelocity:(float)arg2;
- (float)normalizedOffsetOfIndex:(unsigned int)arg1;
@property(nonatomic) float normalizedOffset;
- (void)setOffsetToIndex:(unsigned int)arg1 animated:(BOOL)arg2 completion:(id)arg3;
- (void)setOffsetToIndex:(unsigned int)arg1 animated:(BOOL)arg2;
- (void)cancelScrolling;
- (float)_maxXOffset;
- (void)dealloc;
- (id)init;

@end

