/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "SBAppSwitcherPageContentView.h"

@class SBWallpaperEffectView, SBWindowContextHostManager, UIView<SBWindowContextAppearance>;

@interface SBAppSwitcherContextHostWrapperView : UIView <SBAppSwitcherPageContentView>
{
    SBWindowContextHostManager *_contextHostManager;
    UIView *_containerView;
    UIView<SBWindowContextAppearance> *_contextHostView;
    UIView *_snapshotView;
    SBWallpaperEffectView *_wallpaperEffectView;
    int _orientation;
}

@property(nonatomic) int orientation; // @synthesize orientation=_orientation;
- (void)_viewDidAnimatePresentation:(id)arg1;
- (void)_viewDidAnimateDismissal:(id)arg1;
- (void)_viewDismissing:(id)arg1;
- (void)_viewPresenting:(id)arg1;
- (struct CGAffineTransform)_rotationTransformForOrientation:(int)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)didMoveToSuperview;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 application:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

