/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSHashTable, NSMutableDictionary, NSMutableOrderedSet;

@interface SBAppStatusBarManager : NSObject
{
    NSHashTable *_disableAlphaChangeAssertions;
    NSMutableOrderedSet *_windowLevelOverrideReasons;
    NSMutableDictionary *_windowLevelOverrideMap;
    float _defaultWindowLevel;
}

+ (id)sharedInstance;
- (void)_removeDisableAppStatusBarAlphaChangesAssertion:(id)arg1;
- (void)_addDisableAppStatusBarAlphaChangesAssertion:(id)arg1;
- (void)_updateWindowLevel;
- (void)removeWindowLevelOverrideReason:(id)arg1;
- (void)setWindowLevel:(float)arg1 forOverrideReason:(id)arg2;
- (void)setDefaultWindowLevel:(float)arg1;
- (void)setStatusBarAlpha:(float)arg1;
- (void)hideStatusBar;
- (void)showStatusBar;
- (BOOL)isStatusBarHidden;
- (void)dealloc;
- (id)init;

@end

