/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "_UISettings.h"

@class SBFAnimationSettings, _UIScreenEdgePanRecognizerSettings;

@interface SBAppSliderSettings : _UISettings
{
    int _simplicityOptions;
    SBFAnimationSettings *_dosidoAnimationSettings;
    _UIScreenEdgePanRecognizerSettings *_gestureSettings;
}

+ (id)settingsControllerModule;
@property(retain) _UIScreenEdgePanRecognizerSettings *gestureSettings; // @synthesize gestureSettings=_gestureSettings;
@property(retain) SBFAnimationSettings *dosidoAnimationSettings; // @synthesize dosidoAnimationSettings=_dosidoAnimationSettings;
@property int simplicityOptions; // @synthesize simplicityOptions=_simplicityOptions;
- (BOOL)shouldSimplifyForOptions:(int)arg1;
- (void)setDefaultValues;

@end

