/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "SBAppSwitcherPageContentView.h"

@interface SBAppSliderServiceCellView : UIView <SBAppSwitcherPageContentView>
{
    int _orientation;
}

@property(nonatomic) int orientation; // @synthesize orientation=_orientation;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

