/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class UIStatusBarStyleRequest;

@interface SBAppStatusBarTransitionInfo : NSObject
{
    UIStatusBarStyleRequest *_startStyleRequest;
    int _startOrientation;
    UIStatusBarStyleRequest *_endStyleRequest;
    int _endOrientation;
    int _transition;
    BOOL _zoomOther;
}

@property(nonatomic) BOOL zoomOther; // @synthesize zoomOther=_zoomOther;
@property(nonatomic) int transition; // @synthesize transition=_transition;
@property(nonatomic) int endOrientation; // @synthesize endOrientation=_endOrientation;
@property(copy, nonatomic) UIStatusBarStyleRequest *endStyleRequest; // @synthesize endStyleRequest=_endStyleRequest;
@property(nonatomic) int startOrientation; // @synthesize startOrientation=_startOrientation;
@property(copy, nonatomic) UIStatusBarStyleRequest *startStyleRequest; // @synthesize startStyleRequest=_startStyleRequest;
- (id)description;
- (void)dealloc;

@end

