/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBAlertItem.h"

#import "UIAlertViewDelegate.h"

@class SBApplicationIcon;

@interface SBAppProfileExpiredAlertItem : SBAlertItem <UIAlertViewDelegate>
{
    SBApplicationIcon *_icon;
}

- (BOOL)dismissOnLock;
- (BOOL)shouldShowInLockScreen;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;
- (void)dealloc;
- (id)initWithIcon:(id)arg1;

@end

