/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "SBAppSwitcherPageContentView.h"
#import "SBWallpaperObserver.h"

@class SBFakeStatusBarView;

@interface SBAppSliderHomePageCellView : UIView <SBWallpaperObserver, SBAppSwitcherPageContentView>
{
    UIView *_possiblyRotatedContainer;
    UIView *_nonRotatedContainer;
    UIView *_homeScreenView;
    UIView *_homeSnapshot;
    UIView *_wallpaperView;
    SBFakeStatusBarView *_fakeStatusBar;
    BOOL _usesSnapshots;
    int _snapshotOrientation;
    int _orientation;
}

+ (id)wallpaperSnapshotForZoomFactor:(float)arg1 orientation:(int)arg2;
@property(nonatomic) int orientation; // @synthesize orientation=_orientation;
@property(retain, nonatomic) UIView *homeScreenView; // @synthesize homeScreenView=_homeScreenView;
@property(readonly, nonatomic) UIView *homeSnapshot; // @synthesize homeSnapshot=_homeSnapshot;
- (void)_updateWallpaperView;
- (void)wallpaperDidChangeForVariant:(int)arg1;
- (void)_viewDidAnimatePresentation:(id)arg1;
- (void)_viewDismissing:(id)arg1;
- (void)_viewPresenting:(id)arg1;
- (void)setHomeSnapshot:(id)arg1 inOrientation:(int)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)setLegibilitySettings:(id)arg1;
- (void)_statusBarFrameChanging;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

