/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBWindow.h"

@class SBAssistantRootViewController;

@interface SBAssistantWindow : SBWindow
{
}

- (BOOL)isOpaque;
@property(readonly, nonatomic) SBAssistantRootViewController *assistantRootViewController; // @dynamic assistantRootViewController;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

