/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying.h"
#import "SBAwayListCellButtonHandler.h"
#import "SBUIQuietModePlayability.h"

@class NSDate, NSString, SBUnlockActionContext;

@interface SBAwayListItem : NSObject <SBAwayListCellButtonHandler, SBUIQuietModePlayability, NSCopying>
{
    NSDate *_timestamp;
    BOOL _isNewItem;
    SBUnlockActionContext *_unlockActionContext;
    NSString *_buttonLabel;
}

@property(copy, nonatomic) NSString *buttonLabel; // @synthesize buttonLabel=_buttonLabel;
@property(nonatomic) BOOL isNewItem; // @synthesize isNewItem=_isNewItem;
@property(retain, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
- (BOOL)overridesQuietMode;
- (BOOL)isCritical;
- (BOOL)inertWhenLocked;
- (void)dealloc;
- (BOOL)canBeClearedByNotificationCenter;
- (BOOL)wantsHighlightOnInsert;
- (void)buttonPressed;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

