/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface SBBulletinListSubsection : NSObject
{
    BOOL _showsInLockScreen;
    BOOL _showsMessagePreview;
    NSString *_subsectionID;
}

@property(nonatomic) BOOL showsMessagePreview; // @synthesize showsMessagePreview=_showsMessagePreview;
@property(nonatomic) BOOL showsInLockScreen; // @synthesize showsInLockScreen=_showsInLockScreen;
@property(readonly, nonatomic) NSString *subsectionID; // @synthesize subsectionID=_subsectionID;
- (void)dealloc;
- (id)initWithBulletinListSection:(id)arg1 subsectionID:(id)arg2;

@end

