/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBControlCenterSectionView.h"

@class NSMutableArray;

@interface SBCCButtonLayoutView : SBControlCenterSectionView
{
    NSMutableArray *_buttons;
    float _interButtonPadding;
    struct UIEdgeInsets _contentEdgeInsets;
}

@property(nonatomic) struct UIEdgeInsets contentEdgeInsets; // @synthesize contentEdgeInsets=_contentEdgeInsets;
@property(nonatomic) float interButtonPadding; // @synthesize interButtonPadding=_interButtonPadding;
- (void)layoutSubviews;
- (id)buttons;
- (void)removeButton:(id)arg1;
- (void)addButton:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

