/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBCenterIconZoomAnimator.h"

@class SBCenterAppZoomSettings, UIView;

@interface SBCenterAppIconZoomAnimator : SBCenterIconZoomAnimator
{
    UIView *_appView;
    float _distantScale;
}

@property float distantScale; // @synthesize distantScale=_distantScale;
- (void)_fadeAppForZoomFraction:(float)arg1;
- (void)_zoomAppForZoomFraction:(float)arg1;
- (double)_appZoomDelay;
- (double)_iconZoomDelay;
- (void)_animateToFraction:(float)arg1 afterDelay:(double)arg2 withSharedCompletion:(id)arg3;
- (unsigned int)_numberOfSignificantAnimations;
- (void)_cleanupAnimation;
- (void)_setAnimationFraction:(float)arg1;
- (void)_prepareAnimation;
- (void)_delayedForRotation;
- (void)dealloc;
- (id)initWithFolderController:(id)arg1 appView:(id)arg2;

// Remaining properties
@property(retain, nonatomic) SBCenterAppZoomSettings *settings;

@end

