/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIButton.h"

@class SBIconBlurryBackgroundView, SBIconColorSettings, UIImageView, UIView;

@interface SBCloseBoxView : UIButton
{
    SBIconBlurryBackgroundView *_backgroundView;
    UIView *_whiteTintView;
    UIImageView *_xColorBurnView;
    UIImageView *_xPlusDView;
    SBIconColorSettings *_colorSettings;
    struct CGPoint _wallpaperRelativeCenter;
}

- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setSuppressesBlurryBackgroundChanges:(BOOL)arg1;
- (void)setLegibilityStyle:(int)arg1;
- (void)setWallpaperRelativeCenter:(struct CGPoint)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

