/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

#import "SBControlCenterObserver.h"

@class NSString;

@interface SBControlCenterSectionViewController : UIViewController <SBControlCenterObserver>
{
    id <SBControlCenterSectionViewControllerDelegate> _delegate;
}

+ (Class)viewClass;
@property(nonatomic) id <SBControlCenterSectionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)controlCenterDidFinishTransition;
- (void)controlCenterWillBeginTransition;
- (void)controlCenterDidDismiss;
- (void)controlCenterWillPresent;
- (void)noteSettingsDidUpdate:(id)arg1;
- (struct CGSize)contentSizeForOrientation:(int)arg1;
- (BOOL)enabledForOrientation:(int)arg1;
- (id)view;
@property(readonly, nonatomic) NSString *sectionIdentifier;
- (void)loadView;

@end

