/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "SBControlCenterObserver.h"

@class SBControlCenterContentView, _UIBackdropView;

@interface SBControlCenterContentContainerView : UIView <SBControlCenterObserver>
{
    _UIBackdropView *_backdropView;
    SBControlCenterContentView *_contentView;
    float _contentHeight;
}

@property float contentHeight; // @synthesize contentHeight=_contentHeight;
@property(retain, nonatomic) SBControlCenterContentView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) _UIBackdropView *backdropView; // @synthesize backdropView=_backdropView;
- (void)controlCenterDidFinishTransition;
- (void)controlCenterWillBeginTransition;
- (void)controlCenterDidDismiss;
- (void)controlCenterWillPresent;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

