/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "_UISettings.h"

@class UIColor;

@interface SBControlCenterSettings : _UISettings
{
    BOOL _highlightUsesPlusL;
    BOOL _backgroundDarkensCC;
    float _controlAlpha;
    float _controlAlpha1x;
    float _disabledAlpha;
    float _disabledAlpha1x;
    float _highlightAlpha;
    float _glowAlpha;
    UIColor *_highlightColor;
    float _bounceFriction;
    float _backgroundColorAlpha;
}

+ (id)settingsControllerModule;
@property float backgroundColorAlpha; // @synthesize backgroundColorAlpha=_backgroundColorAlpha;
@property BOOL backgroundDarkensCC; // @synthesize backgroundDarkensCC=_backgroundDarkensCC;
@property float bounceFriction; // @synthesize bounceFriction=_bounceFriction;
@property(retain) UIColor *highlightColor; // @synthesize highlightColor=_highlightColor;
@property float glowAlpha; // @synthesize glowAlpha=_glowAlpha;
@property BOOL highlightUsesPlusL; // @synthesize highlightUsesPlusL=_highlightUsesPlusL;
@property float highlightAlpha; // @synthesize highlightAlpha=_highlightAlpha;
@property float disabledAlpha1x; // @synthesize disabledAlpha1x=_disabledAlpha1x;
@property float disabledAlpha; // @synthesize disabledAlpha=_disabledAlpha;
@property float controlAlpha1x; // @synthesize controlAlpha1x=_controlAlpha1x;
@property float controlAlpha; // @synthesize controlAlpha=_controlAlpha;
- (float)resolvedDisabledAlpha;
- (float)resolvedControlAlpha;
- (void)setDefaultValues;

@end

