/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol SBControlCenterSectionViewControllerDelegate <NSObject>
- (void)sectionWantsControlCenterDismissal:(id)arg1;
- (void)section:(id)arg1 updateStatusText:(id)arg2 reason:(id)arg3;
- (void)noteSectionEnabledStateDidChange:(id)arg1;
@end

