/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@interface SBControlCenterSectionView : UIView
{
    float _edgePadding;
}

@property(nonatomic) float edgePadding; // @synthesize edgePadding=_edgePadding;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;

@end

