/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class NSAttributedString, NSString, UIImage;

@interface SBDefaultBannerTextView : UIView
{
    NSAttributedString *_primaryTextAttributedString;
    NSAttributedString *_primaryTextAttributedStringComponent;
    UIImage *_primaryTextAccessoryImageComponent;
    NSAttributedString *_secondaryTextAttributedString;
    BOOL _secondaryTextItalicized;
    NSAttributedString *_relevanceDateAttributedString;
}

- (void)drawRect:(struct CGRect)arg1;
- (id)_primaryTextAttributedString;
- (void)_invalidatePrimaryTextAttributedString;
- (BOOL)textWillWrapForWidth:(float)arg1;
@property(copy, nonatomic) NSString *relevanceDateText;
- (void)setSecondaryText:(id)arg1 italicized:(BOOL)arg2;
@property(copy, nonatomic) NSString *secondaryText;
@property(retain, nonatomic) UIImage *primaryTextAccessoryImage;
@property(copy, nonatomic) NSString *primaryText;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

