/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "SBDateLabelDelegate.h"
#import "SBUIBannerView.h"

@class SBDefaultBannerTextView, SBUIBannerContext, UIColor, UIImageView, UILabel<SBBulletinDateLabel>;

@interface SBDefaultBannerView : UIView <SBDateLabelDelegate, SBUIBannerView>
{
    SBUIBannerContext *_context;
    id <SBDefaultBannerViewSource> _viewSource;
    UIImageView *_iconImageView;
    UILabel<SBBulletinDateLabel> *_relevanceDateLabel;
    SBDefaultBannerTextView *_textView;
    UIImageView *_attachmentImageView;
    struct CGSize _grabberSize;
    UIView *_grabberView;
}

+ (id)defaultGrabberColor;
- (void)dateLabelDidChange:(id)arg1;
- (void)layoutSubviews;
@property(copy, nonatomic) UIColor *grabberColor;
- (id)bannerContext;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithContext:(id)arg1;

@end

