/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "SBWallpaperObserver.h"

@class SBDockIconListView, SBHighlightView, UIImageView, _SBDockBackgroundView;

@interface SBDockView : UIView <SBWallpaperObserver>
{
    SBDockIconListView *_iconListView;
    SBHighlightView *_highlightView;
    _SBDockBackgroundView *_backgroundView;
    UIImageView *_backgroundImageView;
}

+ (float)defaultHeight;
- (void)wallpaperDidChangeForVariant:(int)arg1;
- (id)_newBackgroundImage;
- (void)setVerticalBackgroundStretch:(float)arg1;
- (void)setBackgroundAlpha:(float)arg1;
- (float)heightForOrientation:(int)arg1;
- (void)layoutSubviews;
- (id)dockListView;
- (void)dealloc;
- (id)initWithDockListView:(id)arg1 forSnapshot:(BOOL)arg2;

@end

