/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBIconImageView.h"

#import "SBFolderIconObserver.h"
#import "SBIconBlurryBackgroundViewObserver.h"

@class NSMutableArray, SBFloatyFolderView, SBFolderIconBackgroundView, UIView, _SBIconGridWrapperView;

@interface SBFolderIconImageView : SBIconImageView <SBFolderIconObserver, SBIconBlurryBackgroundViewObserver>
{
    SBFolderIconBackgroundView *_backgroundView;
    UIView *_pageGridContainer;
    _SBIconGridWrapperView *_leftWrapperView;
    _SBIconGridWrapperView *_rightWrapperView;
    NSMutableArray *_pageElements;
    unsigned int _currentPageIndex;
    SBFloatyFolderView *_crossfadeFolderView;
    UIView *_crossfadeScalingView;
    BOOL _animating;
}

- (void)_showRightMinigrid;
- (void)_showLeftMinigrid;
- (void)_setPageElements:(id)arg1;
- (void)_setupGridViewsInDefaultConfiguration;
- (id)_currentPageElement;
- (id)_folderIcon;
- (struct CGSize)_interiorGridSizeClipRect;
- (struct CGSize)_interPageSpacing;
- (Class)_iconGridImageClass;
- (void)_performScrollingMovingToLeft:(BOOL)arg1 movingToRight:(BOOL)arg2 targetPageIndex:(unsigned int)arg3 targetPageScrollRow:(unsigned int)arg4 newLeftElement:(id)arg5 newRightElement:(id)arg6 animated:(BOOL)arg7;
- (void)_updateRasterization;
- (void)_setAnimating:(BOOL)arg1;
- (void)blurryBackgroundViewDidChangeWhetherBlurring:(id)arg1;
- (void)folderIcon:(id)arg1 didUpdateGridImage:(id)arg2 forListIndex:(unsigned int)arg3 forContainedIconImageUpdate:(id)arg4;
- (void)cleanupAfterFloatyFolderCrossfade;
- (void)setFloatyFolderCrossfadeFraction:(float)arg1;
- (void)prepareToCrossfadeWithFloatyFolderView:(id)arg1 allowFolderInteraction:(BOOL)arg2;
- (void)setSuppressesBlurryBackgroundChanges:(BOOL)arg1;
- (void)setWallpaperRelativeCenter:(struct CGPoint)arg1;
- (void)setBackgroundScale:(float)arg1;
- (id)backgroundView;
- (void)setBackgroundAndIconGridImageAlpha:(float)arg1;
- (void)setIconGridImageAlpha:(float)arg1;
- (struct CGRect)frameForMiniIconAtIndexPath:(id)arg1;
- (struct CGRect)visibleImageRelativeFrameForMiniIconAtIndex:(unsigned int)arg1;
- (struct CGRect)frameForMiniIconAtIndex:(unsigned int)arg1;
- (unsigned int)lastVisibleMiniIconIndex;
- (unsigned int)centerVisibleMiniIconIndex;
- (unsigned int)firstVisibleMiniIconIndex;
- (unsigned int)visibleMiniIconListIndex;
- (unsigned int)visibleMiniIconCount;
- (void)scrollToGapOrTopIfFullOfPage:(unsigned int)arg1 animated:(BOOL)arg2;
- (void)scrollToTopOfPage:(unsigned int)arg1 animated:(BOOL)arg2;
- (void)scrollToFirstGapAnimated:(BOOL)arg1;
- (void)scrollToTopOfFirstPageAnimated:(BOOL)arg1;
- (void)layoutSubviews;
- (id)snapshot;
- (void)prepareForReuse;
- (void)updateImageAnimated:(BOOL)arg1;
- (id)darkeningOverlayImage;
- (id)_generateSquareContentsImage;
- (id)contentsImage;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

