/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "SBWallpaperObserver.h"
#import "_UISettingsKeyObserver.h"

@class SBFolderSettings, SBWallpaperEffectView, UIImageView;

@interface SBFolderBackgroundView : UIView <_UISettingsKeyObserver, SBWallpaperObserver>
{
    SBWallpaperEffectView *_backdropView;
    UIImageView *_backgroundImageView;
    SBFolderSettings *_folderSettings;
}

+ (float)cornerRadiusToInsetContent;
+ (struct CGSize)folderBackgroundSize;
- (void)wallpaperDidChangeForVariant:(int)arg1;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)_configureBackground;
- (void)adjustCornerRadiusForMagnificationFraction:(float)arg1;
- (void)didAnimate;
- (void)willAnimate;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

