/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBIconAnimator.h"

#import "SBIconIndexNodeObserver.h"

@class NSMapTable, NSSet, SBIconListModel, SBIconListView, SBIconZoomSettings;

@interface SBIconZoomAnimator : SBIconAnimator <SBIconIndexNodeObserver>
{
    NSMapTable *_listIconToViewMap;
    NSMapTable *_dockIconToViewMap;
    NSSet *_criticalIconNodeIdentifiers;
    SBIconListModel *_iconListModel;
    SBIconListView *_iconListView;
    SBIconListView *_dockListView;
}

@property(readonly, nonatomic) SBIconListView *dockListView; // @synthesize dockListView=_dockListView;
@property(readonly, nonatomic) SBIconListView *iconListView; // @synthesize iconListView=_iconListView;
@property(retain, nonatomic) NSSet *criticalIconNodeIdentifiers; // @synthesize criticalIconNodeIdentifiers=_criticalIconNodeIdentifiers;
- (void)_invalidateAnimationForSignificantIconModelChangesForReason:(id)arg1;
- (void)_iconModelDidReload;
- (void)_iconModelDidRelayout;
- (void)_clearObservers;
- (void)_setDockListView:(id)arg1;
- (void)_setIconListView:(id)arg1;
- (void)node:(id)arg1 didRemoveContainedNodeIdentifiers:(id)arg2;
- (void)node:(id)arg1 didAddContainedNodeIdentifiers:(id)arg2;
- (void)_cleanupAnimation;
- (void)_prepareAnimation;
- (unsigned int)dockIconCount;
- (unsigned int)listIconCount;
- (void)enumerateIconsAndIconViewsWithHandler:(id)arg1;
- (id)iconViewForIcon:(id)arg1;
- (void)dealloc;
- (id)initWithFolderController:(id)arg1;

// Remaining properties
@property(retain, nonatomic) SBIconZoomSettings *settings;

@end

