/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIPageControl.h"

@class _UILegibilityImageSet;

@interface SBIconListPageControl : UIPageControl
{
    id _delegate;
    _UILegibilityImageSet *_pageIndicatorImageSet;
    _UILegibilityImageSet *_enabledPageIndicatorImageSet;
}

@property(nonatomic) _UILegibilityImageSet *enabledPageIndicatorImageSet; // @synthesize enabledPageIndicatorImageSet=_enabledPageIndicatorImageSet;
@property(nonatomic) _UILegibilityImageSet *pageIndicatorImageSet; // @synthesize pageIndicatorImageSet=_pageIndicatorImageSet;
@property(nonatomic) id <SBIconListPageControlDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_transitionIndicator:(id)arg1 toEnabled:(BOOL)arg2 index:(int)arg3;
- (id)_indicatorViewEnabled:(BOOL)arg1 index:(int)arg2;
- (void)_setIndicatorImage:(id)arg1 toEnabled:(BOOL)arg2;
- (void)setLegibilitySettings:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (float)defaultHeight;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

