/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIImage.h"

#import "SBCountedMapValue.h"

@class SBIconLabelImageParameters;

@interface SBIconLabelLegibilityImage : UIImage <SBCountedMapValue>
{
    SBIconLabelImageParameters *_parameters;
}

+ (void)checkinLegibilityImage:(id)arg1;
+ (id)checkoutLegibilityImageWithLabelImage:(id)arg1 parameters:(id)arg2;
+ (struct CGRect)_legibilityImageRectForLabelImage:(id)arg1 style:(int)arg2;
+ (float)_strengthForLegibilityStyle:(int)arg1;
+ (id)_legibilityImageForIconLabelImage:(id)arg1 parameters:(id)arg2;
+ (id)_legibilityImagePool;
+ (id)_legibilityImageCountedMap;
+ (struct CGSize)_maxLegibilityImageSizeForLabelSize:(struct CGSize)arg1;
@property(readonly) SBIconLabelImageParameters *parameters; // @synthesize parameters=_parameters;
- (id)countedMapKey;
- (void)dealloc;
- (id)_initWithCGImage:(struct CGImage *)arg1 scale:(float)arg2 orientation:(int)arg3 parameters:(id)arg4;

@end

