/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIScrollView.h"

@interface SBIconScrollView : UIScrollView
{
}

- (void)setContentOffset:(struct CGPoint)arg1;
- (BOOL)_scrollsToMakeFirstResponderVisible;
- (BOOL)cancelTouchTracking;

// Remaining properties
@property(nonatomic) id <SBIconScrollViewDelegate> delegate;

@end

