/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIKit.h>

#import "SBIcon.h"
#import "SBIconObserver-Protocol.h"
#import "SBIconAccessoryView-Protocol.h"
#import "_UISettingsKeyObserver-Protocol.h"
#import "SBIconViewDelegate-Protocol.h"
#import "SBIconViewObserver-Protocol.h"

@class NSTimer, SBCloseBoxView, SBFParallaxSettings, SBFolderIconBackgroundView, SBIconImageCrossfadeView, SBIconImageView, UIView, _UILegibilitySettings, _UILegibilityView;

@interface SBIconView : UIView <_UISettingsKeyObserver, SBIconObserver>
{
    SBIcon *_icon;
    NSInteger _iconLocation;
    UIView *_currentImageView;
    SBIconImageView *_iconImageView;
    SBIconImageCrossfadeView *_crossfadeView;
    UIView<SBIconAccessoryView> *_accessoryView;
    SBCloseBoxView *_closeBox;
    SBFParallaxSettings *_closeBoxParallaxSettings;
    CGPoint _wallpaperRelativeCloseBoxCenter;
    _UILegibilityView *_labelView;
    UIView *_updatedMark;
    SBFolderIconBackgroundView *_dropGlow;
    NSUInteger _drawsLabel:1;
    NSUInteger _isEditing:1;
    NSUInteger _isPaused:1;
    NSUInteger _isGrabbed:1;
    NSUInteger _isOverlapping:1;
    NSUInteger _refusesRecipientStatus:1;
    NSUInteger _highlighted:1;
    NSUInteger _launchDisabled:1;
    NSUInteger _isJittering:1;
    NSUInteger _allowJitter:1;
    NSUInteger _touchDownInIcon:1;
    NSUInteger _hideLabel:1;
    NSUInteger _hideUpdatedMark;
    CGPoint _unjitterPoint;
    CGPoint _grabPoint;
    NSTimer *_longPressTimer;
    CGRect _visibleImageRect;
    id<SBIconViewDelegate> _delegate;
    id<SBIconViewObserver> _observer;
    _UILegibilitySettings *_legibilitySettings;
    CGFloat _iconImageAlpha;
    CGFloat _iconAccessoryAlpha;
    CGFloat _iconLabelAlpha;
    CGPoint _wallpaperRelativeImageCenter;
}

+ (id)_jitterTransformAnimation;
+ (id)_jitterPositionAnimation;
+ (CGSize)maxLabelSize;
+ (CGRect)_rectForLayoutMetric:(NSInteger)arg1;
+ (CGSize)defaultVisibleIconImageSize;
+ (CGPoint)defaultIconImageCenter;
+ (CGSize)defaultIconImageSize;
+ (CGFloat)_labelHeight;
+ (CGSize)defaultIconSize;
+ (CGFloat)updatedMarkRightMargin;
+ (BOOL)canShowUpdatedMark;
+ (NSInteger)_defaultIconFormat;

@property(nonatomic) CGPoint wallpaperRelativeImageCenter; // @synthesize wallpaperRelativeImageCenter=_wallpaperRelativeImageCenter;
@property(nonatomic) CGFloat iconLabelAlpha; // @synthesize iconLabelAlpha=_iconLabelAlpha;
@property(nonatomic) CGFloat iconAccessoryAlpha; // @synthesize iconAccessoryAlpha=_iconAccessoryAlpha;
@property(nonatomic) CGFloat iconImageAlpha; // @synthesize iconImageAlpha=_iconImageAlpha;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
@property(nonatomic) SBIconLocation location; // @synthesize location=_iconLocation;
@property(nonatomic, assign) id<SBIconViewObserver> observer; // @synthesize observer=_observer;
@property(nonatomic, assign) id<SBIconViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SBIcon *icon;
@property(nonatomic) BOOL isEditing;

- (void)iconLaunchEnabledDidChange:(SBIcon *)icon; /* SBIconObserver */
- (void)iconAccessoriesDidUpdate:(SBIcon *)icon; /* SBIconObserver */
- (BOOL)_shouldAnimatePropertyWithKey:(NSString *)key;
- (void)_updateProgressAnimated:(BOOL)animated;
- (void)prepareForRecycling;
- (void)settings:(id)settings changedValueForKey:(NSString *)key;
- (BOOL)_delegateTapAllowed;
- (void)_delegateTouchEnded:(BOOL)ended;
- (UIEdgeInsets)snapshotEdgeInsets;
- (BOOL)pointInside:(CGPoint)point withEvent:(UIEvent *)event;
- (void)_closeBoxTapped;
- (BOOL)_isShowingCloseBox;
- (void)_updateCloseBoxAnimated:(BOOL)animated;
- (void)_applyEditingStateAnimated:(BOOL)animated;

- (void)setIsEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setTouchDownInIcon:(BOOL)arg1;
- (BOOL)isTouchDownInIcon;
- (void)touchesEnded:(NSArray *)touches withEvent:(UIEvent *)event;
- (void)touchesMoved:(NSArray *)touches withEvent:(UIEvent *)event;
- (void)touchesBegan:(NSArray *)touches withEvent:(UIEvent *)event;
- (void)touchesCancelled:(NSArray *)touches withEvent:(UIEvent *)event;
- (void)cancelLongPressTimer;
- (void)longPressTimerFired;
- (void)cleanupAfterImageCrossfade;
- (void)setImageCrossfadeMorphFraction:(CGFloat)arg1;
- (void)setImageCrossfadeFadeFraction:(CGFloat)arg1;
- (void)prepareToCrossfadeImageWithView:(id)arg1 maskCorners:(BOOL)arg2 trueCrossfade:(BOOL)arg3 anchorPoint:(CGPoint)arg4;
- (void)prepareToCrossfadeImageWithView:(id)arg1 maskCorners:(BOOL)arg2 trueCrossfade:(BOOL)arg3;
- (id)dropGlow;
- (void)removeDropGlow;
- (void)showDropGlow:(BOOL)showDropGlow;
- (void)prepareDropGlow;
- (void)setIsOverlapping:(BOOL)isOverlapping;
- (BOOL)isGrabbed;
- (void)setIsGrabbed:(BOOL)isGrabbed;
- (double)grabDurationForEvent:(UIEvent *)event;
- (BOOL)canReceiveGrabbedIcon:(SBIcon *)icon; /* called during folder creation */
- (void)setRefusesRecipientStatus:(BOOL)refusesRecepientStatus;
- (void)setIconPosition:(CGPoint)position;
- (void)removeAllIconAnimations;
- (void)setAllowJitter:(BOOL)allowJitter;
- (void)_updateJitter;
- (void)setFrame:(CGRect)frame;
- (BOOL)isInDock;
- (void)setHighlighted:(BOOL)highlighted;
- (BOOL)isHighlighted;
- (BOOL)allowsTapWhileEditing;
- (void)_updateBrightness;
- (BOOL)pointMostlyInside:(CGPoint)point withEvent:(UIEvent *)event;
- (id)_automationID;
- (void)_createAccessoryViewIfNecessary;
- (void)_updateAccessoryViewWithAnimation:(BOOL)withAnimation;
- (void)_updateIconImageViewAnimated:(BOOL)animated;
- (void)_updateUpdatedMark;
- (id)_legibilitySettingsWithPrimaryColor:(UIColor *)color;
- (id)_legibilitySettingsWithParameters:(id)params; /* NSDictionary? */
- (void)_updateLabel;
- (id)_labelImageParameters;
- (void)invalidateLabelLayoutGeometry;
- (void)_updateAdaptiveColors;
- (void)setSuppressesBlurryBackgroundChanges:(BOOL)suppress;
- (id)_labelImage;
- (id)_iconImageView;
- (CGPoint)_centerForCloseBoxRelativeToVisibleImageFrame:(CGRect)frame;
- (CGPoint)_centerForCloseBox;
- (CGRect)_frameForAccessoryView;
- (CGRect)_frameForUpdatedMarkWithLabelFrame:(CGRect)frame;
- (CGRect)_frameForLabel;
- (CGFloat)_labelVerticalOffset;
- (CGRect)_frameForImageView;
- (void)layoutSubviews;
- (void)setUpdatedMarkHidden:(BOOL)hidden;
- (void)setLabelHidden:(BOOL)hidden;
- (void)_applyIconLabelAlpha:(CGFloat)alpha;
- (void)_applyIconAccessoryAlpha:(CGFloat)alpha;
- (void)_applyIconImageAlpha:(CGFloat)alpha;
- (void)setIconImageAndAccessoryAlpha:(CGFloat)alpha;
- (CGSize)iconImageVisibleSize;
- (CGPoint)iconImageCenter;
- (CGRect)iconImageFrame;
- (id)iconImageSnapshot;
- (void)swapInIcon:(id)icon;
- (void)_setIcon:(SBIcon *)icon animated:(BOOL)animated;
- (void)setPaused:(BOOL)paused;
- (void)dealloc;
- (id)initWithDefaultSize;

@end

