/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying.h"
#import "NSMutableCopying.h"

@class NSString, UIFont;

@interface SBIconLabelImageParameters : NSObject <NSCopying, NSMutableCopying>
{
    UIFont *_font;
    NSString *_text;
    BOOL _containsNonLatinLikeCharacters;
    BOOL _containsEmoji;
    BOOL _canEllipsize;
    struct CGSize _maxSize;
    int _style;
}

@property(readonly, nonatomic) int style; // @synthesize style=_style;
@property(readonly, nonatomic) BOOL containsEmoji; // @synthesize containsEmoji=_containsEmoji;
@property(readonly, nonatomic) BOOL containsNonLatinLikeCharacters; // @synthesize containsNonLatinLikeCharacters=_containsNonLatinLikeCharacters;
@property(readonly, nonatomic) BOOL canEllipsize; // @synthesize canEllipsize=_canEllipsize;
@property(readonly, nonatomic) UIFont *font; // @synthesize font=_font;
@property(readonly, nonatomic) struct CGSize maxSize; // @synthesize maxSize=_maxSize;
@property(readonly, nonatomic) NSString *text; // @synthesize text=_text;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (BOOL)colorspaceIsGrayscale;
- (void)dealloc;
- (id)initWithParameters:(id)arg1;

@end

