/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "_SBIconWallpaperColorClient.h"

@interface SBIconBlurryBackgroundView : UIView <_SBIconWallpaperColorClient>
{
    struct CGRect _wallpaperRelativeBounds;
    BOOL _isBlurring;
    BOOL _suppressesExternalUpdates;
    id <SBIconBlurryBackgroundViewObserver> _observer;
    id _wantsBlurEvaluator;
    struct CGPoint _wallpaperRelativeCenter;
}

@property(nonatomic, getter=isSuppressingExternalUpdates) BOOL suppressesExternalUpdates; // @synthesize suppressesExternalUpdates=_suppressesExternalUpdates;
@property(copy, nonatomic) id wantsBlurEvaluator; // @synthesize wantsBlurEvaluator=_wantsBlurEvaluator;
@property(readonly, nonatomic) BOOL isBlurring; // @synthesize isBlurring=_isBlurring;
@property(nonatomic) struct CGPoint wallpaperRelativeCenter; // @synthesize wallpaperRelativeCenter=_wallpaperRelativeCenter;
@property(nonatomic) id <SBIconBlurryBackgroundViewObserver> observer; // @synthesize observer=_observer;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)setBlurring:(BOOL)arg1;
- (void)setWallpaperColor:(struct CGColor *)arg1 phase:(struct CGSize)arg2;
- (BOOL)wantsBlur:(id)arg1;
- (struct CGRect)wallpaperRelativeBounds;
- (void)didAddSubview:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

