/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "SBIconIndexNode-Protocol.h"

@class NSHashTable, UIImage, SBFolder;

typedef NS_ENUM(NSInteger, SBIconLocation) {
    SBIconLocationHomeScreen = 0,
    SBIconLocationDock       = 1,
    SBIconLocationSwitcher   = 2
};

@interface SBIcon : NSObject <SBIconIndexNode>
{
    NSHashTable *_observers;
    id _badgeNumberOrString;
    NSUInteger _uninstalled:1;
    UIImage *_cachedIconImages[14];
}

+ (id)memoryMappedIconImageOfSize:(CGSize)arg1 scale:(CGFloat)arg2 withDrawing:(id)arg3;
+ (id)memoryMappedIconImageForIconImage:(id)arg1;
+ (id)_iconImageOfSize:(CGSize)arg1 scale:(CGFloat)arg2 failGracefully:(BOOL)arg3 drawing:(id)arg4;
+ (id)_iconImagesMemoryPool;
- (BOOL)canReceiveGrabbedIcon;
- (id)folderFallbackTitle;
- (id)folderTitleOptions;
- (id)uninstallAlertCancelTitle;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertBodyForAppWithDocumentUpdatesPending;
- (id)uninstallAlertBodyForAppWithDocumentsInCloud;
- (id)uninstallAlertBody;
- (id)uninstallAlertTitleForAppWithDocumentUpdatesPending;
- (id)uninstallAlertTitleForAppWithDocumentsInCloud;
- (id)uninstallAlertTitle;
- (BOOL)isUninstalled;
- (void)setUninstalled;
- (void)completeUninstall;
- (BOOL)allowsUninstall;
- (BOOL)progressIsPaused;
- (CGFloat)progressPercent;
- (NSInteger)progressState;
- (void)launchFromLocation:(SBIconLocation)location;
- (id)automationID;
- (BOOL)isRecentlyUpdated;
- (void)setBadge:(id)badge; /* NSNumber or NSString. This is a shitty interface */
- (void)noteBadgeDidChange;
- (NSInteger)accessoryTypeForLocation:(SBIconLocation)location;
- (id)accessoryTextForLocation:(SBIconLocation)location;
- (id)badgeNumberOrString;
- (NSInteger)badgeValue;
- (void)reloadIconImagePurgingImageCache:(BOOL)arg1;
- (void)reloadIconImage;
- (void)purgeCachedImages;
- (id)gridCellImage;
- (id)getGenericIconImage:(NSInteger)arg1;
- (id)getUnmaskedIconImage:(NSInteger)arg1;
- (id)getIconImage:(NSInteger)arg1;
- (id)getStandardIconImageForLocation:(SBIconLocation)arg1;
- (BOOL)shouldCacheImageForFormat:(NSInteger)arg1;
- (id)generateIconImage:(NSInteger)arg1;
- (BOOL)launchEnabled;
- (id)tags;
- (BOOL)matchesEntity:(id)arg1;
- (NSInteger)localizedCompareDisplayNames:(id)arg1;
- (BOOL)canEllipsizeLabel;
- (id)displayName;
- (void)localeChanged;
- (BOOL)matchesRepresentation:(id)arg1;
- (id)representation;
- (void)dealloc;
- (id)init;
- (NSInteger)iconFormatForLocation:(SBIconLocation)location;
@property(readonly, nonatomic) BOOL shouldWarmUp;
- (BOOL)hasCachedImageForLocation:(SBIconLocation)location;
- (id)nodeDescriptionWithPrefix:(id)arg1;
- (void)removeNodeObserver:(id)arg1;
- (void)addNodeObserver:(id)arg1;
- (id)nodesAlongIndexPath:(id)arg1 consumedIndexes:(NSUInteger)arg2;
- (id)indexPathsForContainedNodeIdentifier:(id)arg1 prefixPath:(id)arg2;
- (id)containedNodeIdentifiers;
- (BOOL)containsNodeIdentifier:(id)arg1;
- (id)nodeIdentifier;
- (BOOL)hasObserver:(id)arg1;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (id)description;
- (id)application;
- (BOOL)isApplicationIcon;
- (BOOL)isBookmarkIcon;
- (id)appPlaceholder;
- (BOOL)isDownloadingIcon;
- (BOOL)isUserInstalledApplicationIcon;
- (BOOL)isWebApplicationIcon;
- (BOOL)hasFolderIconView;
- (SBFolder *)folder;
- (BOOL)isFolderIcon;
- (id)applicationBundleID;
- (id)webClip;
- (NSString *)leafIdentifier;
- (BOOL)isLeafIcon;
- (Class)iconImageViewClassForLocation:(SBIconLocation)location;
- (Class)iconViewClassForLocation:(SBIconLocation)location;
- (void)_notifyLaunchEnabledDidChange;
- (void)_notifyAccessoriesDidUpdate;
- (void)_notifyImageDidUpdate;
- (BOOL)iconAppearsInNewsstand;
- (BOOL)isNewsstandApplicationIcon;
- (BOOL)isNewsstandIcon;
- (BOOL)isEmptyPlaceholder;
- (BOOL)isGrabbedIconPlaceholder;
- (BOOL)isPlaceholder;

@end

