/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "_UISettings.h"

@interface SBLegibilitySettings : _UISettings
{
    float _slideToUnlockDarkShadowStrength;
    float _slideToUnlockLightShadowStrength;
    float _cameraGrabberDarkShadowStrength;
    float _cameraGrabberLightShadowStrength;
    float _timeDarkShadowStrength;
    float _timeLightShadowStrength;
    float _dateDarkShadowStrength;
    float _dateLightShadowStrength;
    float _legalDarkShadowStrength;
    float _legalLightShadowStrength;
    float _iconLabelDarkShadowStrength;
    float _iconLabelLightShadowStrength;
    float _folderTitleDarkShadowStrength;
    float _folderTitleLightShadowStrength;
    float _timerTextDarkShadowStrength;
    float _timerTextLightShadowStrength;
    float _timerDialDarkShadowStrength;
    float _timerDialLightShadowStrength;
}

+ (id)settingsControllerModule;
@property float timerDialLightShadowStrength; // @synthesize timerDialLightShadowStrength=_timerDialLightShadowStrength;
@property float timerDialDarkShadowStrength; // @synthesize timerDialDarkShadowStrength=_timerDialDarkShadowStrength;
@property float timerTextLightShadowStrength; // @synthesize timerTextLightShadowStrength=_timerTextLightShadowStrength;
@property float timerTextDarkShadowStrength; // @synthesize timerTextDarkShadowStrength=_timerTextDarkShadowStrength;
@property float folderTitleLightShadowStrength; // @synthesize folderTitleLightShadowStrength=_folderTitleLightShadowStrength;
@property float folderTitleDarkShadowStrength; // @synthesize folderTitleDarkShadowStrength=_folderTitleDarkShadowStrength;
@property float iconLabelLightShadowStrength; // @synthesize iconLabelLightShadowStrength=_iconLabelLightShadowStrength;
@property float iconLabelDarkShadowStrength; // @synthesize iconLabelDarkShadowStrength=_iconLabelDarkShadowStrength;
@property float legalLightShadowStrength; // @synthesize legalLightShadowStrength=_legalLightShadowStrength;
@property float legalDarkShadowStrength; // @synthesize legalDarkShadowStrength=_legalDarkShadowStrength;
@property float dateLightShadowStrength; // @synthesize dateLightShadowStrength=_dateLightShadowStrength;
@property float dateDarkShadowStrength; // @synthesize dateDarkShadowStrength=_dateDarkShadowStrength;
@property float timeLightShadowStrength; // @synthesize timeLightShadowStrength=_timeLightShadowStrength;
@property float timeDarkShadowStrength; // @synthesize timeDarkShadowStrength=_timeDarkShadowStrength;
@property float cameraGrabberLightShadowStrength; // @synthesize cameraGrabberLightShadowStrength=_cameraGrabberLightShadowStrength;
@property float cameraGrabberDarkShadowStrength; // @synthesize cameraGrabberDarkShadowStrength=_cameraGrabberDarkShadowStrength;
@property float slideToUnlockLightShadowStrength; // @synthesize slideToUnlockLightShadowStrength=_slideToUnlockLightShadowStrength;
@property float slideToUnlockDarkShadowStrength; // @synthesize slideToUnlockDarkShadowStrength=_slideToUnlockDarkShadowStrength;
- (float)timerDialStrengthForStyle:(int)arg1;
- (float)timerTextStrengthForStyle:(int)arg1;
- (float)folderTitleStrengthForStyle:(int)arg1;
- (float)iconLabelStrengthForStyle:(int)arg1;
- (float)legalStrengthForStyle:(int)arg1;
- (float)dateStrengthForStyle:(int)arg1;
- (float)timeStrengthForStyle:(int)arg1;
- (float)cameraGrabberStrengthForStyle:(int)arg1;
- (float)slideToUnlockStrengthForStyle:(int)arg1;
- (void)setDefaultValues;

@end

