/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBIconImageView.h"

#import "SBControlCenterObserver.h"

@interface SBLiveIconImageView : SBIconImageView <SBControlCenterObserver>
{
    unsigned int _pauseCauses;
}

+ (void)_displayDidDeactivate:(id)arg1;
+ (void)_displayWillActivate:(id)arg1;
+ (void)initialize;
- (void)controlCenterDidFinishTransition;
- (void)controlCenterWillBeginTransition;
- (void)controlCenterDidDismiss;
- (void)controlCenterWillPresent;
- (void)_activeDisplayChanged:(id)arg1;
- (void)didMoveToWindow;
- (id)snapshot;
- (void)prepareForReuse;
- (void)updateImageAnimated:(BOOL)arg1;
- (void)updateAnimatingState;
- (void)setPaused:(BOOL)arg1;
- (BOOL)isAnimationAllowed;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

