/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

#import "BBObserverDelegate.h"

@class BBBulletin, BBObserver, NSDate, NSTimer;

@interface SBLockScreenTimerViewController : UIViewController <BBObserverDelegate>
{
    BOOL _enabled;
    NSTimer *_updateTimer;
    NSDate *_endDate;
    BBObserver *_observer;
    id <SBLockScreenTimerViewControllerDelegate> _delegate;
    BBBulletin *_timerBulletin;
}

@property(retain) BBBulletin *timerBulletin; // @synthesize timerBulletin=_timerBulletin;
@property id <SBLockScreenTimerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)observer:(id)arg1 purgeReferencesToBulletinID:(id)arg2;
- (void)observer:(id)arg1 noteInvalidatedBulletinIDs:(id)arg2;
- (void)observer:(id)arg1 removeBulletin:(id)arg2;
- (void)observer:(id)arg1 addBulletin:(id)arg2 forFeed:(unsigned int)arg3;
- (void)setContentAlpha:(float)arg1;
- (void)_updateTimerLabelView;
- (void)_updateTimerFired;
- (void)_startTimer;
- (void)_stopTimer;
- (BOOL)_isEndDateValid;
- (id)timerView;
- (void)setEndDate:(id)arg1;
- (void)setTimerHidden:(BOOL)arg1;
- (BOOL)isTimerActive;
- (void)setEnabled:(BOOL)arg1;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

