/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBLockStateAggregator : NSObject
{
    unsigned int _lockState;
}

+ (id)sharedInstance;
- (void)_updateLockState;
- (BOOL)hasAnyLockState;
- (unsigned int)lockState;
- (id)description;
- (id)_descriptionForLockState:(unsigned int)arg1;
- (void)dealloc;
- (id)init;

@end

