/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class NSDate, SBLockScreenTimerDialView, UILabel, _UILegibilityLabel;

@interface SBLockScreenTimerView : UIView
{
    NSDate *_endDate;
    SBLockScreenTimerDialView *_timerDial;
    UILabel *_layoutLabel;
    _UILegibilityLabel *_timerLabel;
}

+ (float)interItemSpacing;
+ (id)_timerFont;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (float)baselineOffsetFromBottom;
- (void)setTimerHidden:(BOOL)arg1;
- (void)updateTimerLabel;
- (void)setEndDate:(id)arg1;
- (void)setLegibilitySettings:(id)arg1 textStrength:(float)arg2 dialStrength:(float)arg3;
- (id)_newTimerDialForSettings:(id)arg1 strength:(float)arg2;
- (id)_newLegibilityLabelForSettings:(id)arg1 strength:(float)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

