/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBLockScreenBulletinCell.h"

@interface SBLockScreenSystemAlertCell : SBLockScreenBulletinCell
{
}

+ (BOOL)wantsUnlockActionText;
+ (float)rowHeightForTitle:(id)arg1 body:(id)arg2 rowWidth:(float)arg3;
- (void)layoutSubviews;

@end

