/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBAlert.h"

@class SBUnlockActionContext;

@interface SBLockScreenViewControllerBase : SBAlert
{
    id <SBLockScreenViewControllerDelegate> _delegate;
    SBUnlockActionContext *_customUnlockActionContext;
}

@property(nonatomic) id <SBLockScreenViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)allPendingAlertItems;
- (BOOL)hasSuperModalAlertItems;
- (id)currentAlertItem;
- (id)dequeueAllPendingSuperModalAlertItems;
- (void)deactivateAlertItem:(id)arg1;
- (BOOL)activateAlertItem:(id)arg1;
- (BOOL)wantsToHandleAlert:(id)arg1;
- (BOOL)handleExternalKeyDownEvent;
- (void)noteResetRestoreStateUpdated;
- (void)noteDeviceBlockedStatusUpdated;
- (BOOL)isLockScreenVisible;
- (BOOL)isShowingOverheatUI;
- (void)shakeSlideToUnlockTextWithCustomText:(id)arg1;
- (id)activationBlockAnimated:(SEL)arg1;
- (void)updateInterfaceIfNecessary;
- (void)setShowingMediaControls:(BOOL)arg1;
- (BOOL)isShowingMediaControls;
- (void)updateOrientationForUndim;
- (BOOL)lockScreenBulletinControllerIsActive;
- (void)setCustomUnlockActionContext:(id)arg1;
- (id)_customUnlockActionContext;
- (id)currentUnlockActionContext;
- (BOOL)lockScreenIsShowingBulletins;
- (BOOL)shouldShowLockStatusBarTime;
- (BOOL)shouldShowSlideshowButton;
- (BOOL)handleMenuButtonHeld;
- (BOOL)handleMenuButtonTap;
- (void)noteExitingLostMode;
- (void)prepareToEnterLostMode;
- (void)updateCardItem:(id)arg1;
- (void)deactivateCardItem:(id)arg1;
- (void)activateCardItem:(id)arg1 animated:(BOOL)arg2;
- (struct CGRect)defaultContentRegionForPluginController:(id)arg1 withOrientation:(int)arg2;
- (void)disableLockScreenBundleWithName:(id)arg1 deactivationContext:(id)arg2;
- (void)enableLockScreenBundleWithName:(id)arg1 activationContext:(id)arg2;
- (id)activeLockScreenPluginController;
- (BOOL)isLockScreenPluginViewVisible;
- (BOOL)hasActiveUIAccessories;
- (void)setInScreenOffMode:(BOOL)arg1;
- (BOOL)isInScreenOffMode;
- (void)startLockScreenFadeInAnimationForSource:(int)arg1;
- (BOOL)canRelockForAutoDimTimer;
- (BOOL)wantsScreenToAutoDim;
- (void)prepareForMesaUnlockWithCompletion:(id)arg1;
- (void)biometricEventMonitor:(id)arg1 handleBiometricEvent:(unsigned int)arg2;
- (BOOL)isHidingPasscodeViewDuringCall;
- (void)setForcesPasscodeViewDuringCall:(BOOL)arg1;
- (void)prepareToReturnToCameraFromCall;
- (void)cancelReturnToCameraAfterCall;
- (BOOL)shouldReturnToCameraAfterCall;
- (void)handlePhoneAppExitedIfNecessary;
- (void)noteStartingPhoneCallWhileUILocked;
- (BOOL)isMakingEmergencyCall;
- (void)emergencyDialerExitedWithError:(id)arg1;
- (void)exitEmergencyDialerAnimated:(BOOL)arg1;
- (void)launchEmergencyDialer;
- (void)dismissCameraImmediately;
- (void)activateCameraAnimated:(BOOL)arg1;
- (void)activateCamera;
- (BOOL)cameraIsVisible;
- (BOOL)cameraIsActive;
- (BOOL)_isLockAlert;
- (void)prepareForExternalUIUnlock;
- (void)deactivate;
- (void)activate;
- (BOOL)_wantsToAnimateFromPasscodeLockOnFailedPasscodeAttemptAndBlocked;
- (void)finishUIUnlockFromSource:(int)arg1;
- (void)attemptToUnlockUIFromNotification;
- (BOOL)canBeDeactivatedForUIUnlockFromSource:(int)arg1;
- (void)prepareForUIUnlock;
- (BOOL)wantsPasscodeLockForUIUnlockFromSource:(int)arg1 withOptions:(id)arg2;
- (BOOL)isPasscodeLockVisible;
- (void)setPasscodeLockVisible:(BOOL)arg1 animated:(BOOL)arg2 withUnlockSource:(int)arg3 andOptions:(id)arg4;
- (void)setPasscodeLockVisible:(BOOL)arg1 animated:(BOOL)arg2 completion:(id)arg3;
- (void)setPasscodeLockVisible:(BOOL)arg1 animated:(BOOL)arg2;
- (BOOL)allowSystemGestureAtLocation:(struct CGPoint)arg1;
- (void)_transitionWallpaperFromLockWithOptionalOutTimingFunction:(id)arg1 adjustWindowLevel:(BOOL)arg2;
- (void)_transitionWallpaperFromLock;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;

@end

