/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "_UISettings.h"

@class SBBounceSettings, SBFAnimationSettings, SBLockScreenPasscodeSettings, SBSlideToUnlockFailureRecognizerSettings;

@interface SBLockScreenSettings : _UISettings
{
    BOOL _alwaysPutPluginsBelowScrollView;
    SBBounceSettings *_verticalBounceSettings;
    SBBounceSettings *_horizontalBounceSettings;
    SBLockScreenPasscodeSettings *_passcodeSettings;
    SBSlideToUnlockFailureRecognizerSettings *_slideToUnlockFailureRecognizerSettings;
    SBFAnimationSettings *_unlockToPhoneWallpaperOutSettings;
    SBFAnimationSettings *_unlockToPhoneWallpaperInSettings;
    SBFAnimationSettings *_unlockWallpaperOutSettings;
    SBFAnimationSettings *_unlockWallpaperInSettings;
    float _lockToUnlockSlideCompletionPercentage;
    float _lockToUnlockSlideCompletionPercentageIPad;
    float _unlockSlideForIdleTimerDisabledPercentage;
    float _unlockSlideForIdleTimerDisabledPercentageIPad;
    float _notificationScrollForIdleTimerDisabledOffset;
    float _notificationScrollForIdleTimerDisabledOffsetIPad;
    float _unlockSwipeWallpaperAlpha;
}

+ (id)settingsControllerModule;
@property BOOL alwaysPutPluginsBelowScrollView; // @synthesize alwaysPutPluginsBelowScrollView=_alwaysPutPluginsBelowScrollView;
@property float unlockSwipeWallpaperAlpha; // @synthesize unlockSwipeWallpaperAlpha=_unlockSwipeWallpaperAlpha;
@property float notificationScrollForIdleTimerDisabledOffsetIPad; // @synthesize notificationScrollForIdleTimerDisabledOffsetIPad=_notificationScrollForIdleTimerDisabledOffsetIPad;
@property float notificationScrollForIdleTimerDisabledOffset; // @synthesize notificationScrollForIdleTimerDisabledOffset=_notificationScrollForIdleTimerDisabledOffset;
@property float unlockSlideForIdleTimerDisabledPercentageIPad; // @synthesize unlockSlideForIdleTimerDisabledPercentageIPad=_unlockSlideForIdleTimerDisabledPercentageIPad;
@property float unlockSlideForIdleTimerDisabledPercentage; // @synthesize unlockSlideForIdleTimerDisabledPercentage=_unlockSlideForIdleTimerDisabledPercentage;
@property float lockToUnlockSlideCompletionPercentageIPad; // @synthesize lockToUnlockSlideCompletionPercentageIPad=_lockToUnlockSlideCompletionPercentageIPad;
@property float lockToUnlockSlideCompletionPercentage; // @synthesize lockToUnlockSlideCompletionPercentage=_lockToUnlockSlideCompletionPercentage;
@property(retain) SBFAnimationSettings *unlockWallpaperInSettings; // @synthesize unlockWallpaperInSettings=_unlockWallpaperInSettings;
@property(retain) SBFAnimationSettings *unlockWallpaperOutSettings; // @synthesize unlockWallpaperOutSettings=_unlockWallpaperOutSettings;
@property(retain) SBFAnimationSettings *unlockToPhoneWallpaperInSettings; // @synthesize unlockToPhoneWallpaperInSettings=_unlockToPhoneWallpaperInSettings;
@property(retain) SBFAnimationSettings *unlockToPhoneWallpaperOutSettings; // @synthesize unlockToPhoneWallpaperOutSettings=_unlockToPhoneWallpaperOutSettings;
@property(retain) SBSlideToUnlockFailureRecognizerSettings *slideToUnlockFailureRecognizerSettings; // @synthesize slideToUnlockFailureRecognizerSettings=_slideToUnlockFailureRecognizerSettings;
@property(retain) SBLockScreenPasscodeSettings *passcodeSettings; // @synthesize passcodeSettings=_passcodeSettings;
@property(retain) SBBounceSettings *horizontalBounceSettings; // @synthesize horizontalBounceSettings=_horizontalBounceSettings;
@property(retain) SBBounceSettings *verticalBounceSettings; // @synthesize verticalBounceSettings=_verticalBounceSettings;
- (void)setDefaultValues;

@end

