/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "_UISettings.h"

@interface SBLockScreenPasscodeSettings : _UISettings
{
    int _scrollBehavior;
    float _fixedHysteresis;
    float _percentOfNextButtonIncluded;
}

+ (id)settingsControllerModule;
@property(nonatomic) float percentOfNextButtonIncluded; // @synthesize percentOfNextButtonIncluded=_percentOfNextButtonIncluded;
@property(nonatomic) float fixedHysteresis; // @synthesize fixedHysteresis=_fixedHysteresis;
@property(nonatomic) int scrollBehavior; // @synthesize scrollBehavior=_scrollBehavior;
- (void)setDefaultValues;

@end

