/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CADisplayLink, NSMutableDictionary, NSTimer, SBLockScreenNotificationTableView;

@interface SBLockScreenNotificationListView : UIView <UITableViewDataSource, UITableViewDelegate>
{
    SBLockScreenNotificationTableView *_tableView;
    UIView *_tableHeaderView;
    UIView *_tableFooterView;
    UIView *_topPocketView;
    UIView *_bottomPocketView;
    UIView *_containerView;
    id <SBLockScreenNotificationViewDelegate> _delegate;
    id <SBLockScreenNotificationModel> _model;
    CADisplayLink *_displayLink;
    float _currentTextAlpha;
    double _fadeStartTimestamp;
    NSTimer *_oldTextDisabledTimer;
    unsigned int _indexOfNewItem;
    BOOL _notificationCellIsScrollingToPasscode;
    float _notificationScrollDecelerationRatio;
    NSMutableDictionary *_heightForListItemCache;
    float _totalContentHeight;
    float _startingScrollOffset;
    float _lastDistanceScrolled;
    BOOL _updateCellsToVisibleOnPluginWillDisable;
}

@property(nonatomic) BOOL updateCellsToVisibleOnPluginWillDisable; // @synthesize updateCellsToVisibleOnPluginWillDisable=_updateCellsToVisibleOnPluginWillDisable;
@property(nonatomic) id <SBLockScreenNotificationModel> model; // @synthesize model=_model;
@property(nonatomic) id <SBLockScreenNotificationViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_cellTextFadeTimerFired:(id)arg1;
- (void)_textDisabledTimerFired:(id)arg1;
- (void)_clearTextFadeTimer;
- (void)_clearTextDisabledTimer;
- (void)_resetAllFadeTimers;
- (void)_disableExistingContent;
- (struct UIEdgeInsets)_contentViewInsets;
- (BOOL)_disableIdleTimer:(BOOL)arg1;
- (void)_pluginWillDisable:(id)arg1;
- (void)updateForRemovalOfItems;
- (void)updateForRemovalOfItemAtIndex:(unsigned int)arg1 removedItem:(id)arg2;
- (void)_postludeForUpdateForRemoval:(BOOL)arg1;
- (void)updateForModificationOfItemWithOldIndex:(unsigned int)arg1 andNewIndex:(unsigned int)arg2;
- (void)updateForAdditionOfItemAtIndex:(unsigned int)arg1 allowHighlightOnInsert:(BOOL)arg2;
- (int)_rowAnimationForDelete;
- (int)_rowAnimationForInsert;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)_scrollingEndedInScrollView:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)_setNonSelectedCellsToVisible:(BOOL)arg1 withSelectedCell:(id)arg2;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)_setContentForTableCell:(id)arg1 withItem:(id)arg2 atIndexPath:(id)arg3;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)lockScreenDidEndScrollingOnPage:(int)arg1;
- (void)scrollToTopOfListAnimated:(BOOL)arg1;
- (void)setInScreenOffMode:(BOOL)arg1;
- (void)_updateTotalContentHeight;
- (void)_updateBottomShadowVisibility;
- (id)_tableFooterView;
- (id)_tableHeaderView;
- (void)layoutSubviews;
- (void)prepareForRemoval;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)_pocketLineColor;

@end

