/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBLockOverlayView.h"

@class SBLockOverlayStylePropertiesFactory, UIButton, UIImageView, UILabel, UIView, _UILegibilitySettings;

@interface SBLockScreenBuddyView : SBLockOverlayView
{
    UILabel *_titleLabel;
    UIView *_logoImageContainer;
    UIImageView *_logoImageView;
    BOOL _usesWhiteLogo;
    int _viewState;
    SBLockOverlayStylePropertiesFactory *_underlayPropertiesFactory;
    _UILegibilitySettings *_legibilitySettings;
    id <SBLockScreenBuddyViewDelegate> _delegate;
    unsigned int _style;
    UIView *_activationInfoView;
    UIButton *_infoButton;
}

@property(retain, nonatomic) UIButton *infoButton; // @synthesize infoButton=_infoButton;
@property(retain, nonatomic) UIView *activationInfoView; // @synthesize activationInfoView=_activationInfoView;
@property(nonatomic) unsigned int style; // @synthesize style=_style;
@property(nonatomic) id <SBLockScreenBuddyViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)legibilitySettings;
- (id)underlayPropertiesFactory;
- (void)layoutSubviews;
- (void)configureOverlayPropertiesForStyle:(unsigned int)arg1;
- (BOOL)isFakeLogoHidden;
- (void)_toggleViewState;
- (void)setViewState:(int)arg1;
- (void)setTitleLanguage:(id)arg1;
- (void)setTitleString:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 useWhiteLogo:(BOOL)arg2;

@end

