/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBLockScreenBulletinCell.h"

#import "SBDateLabelDelegate.h"

@class SBSnoozedAlarmDateLabel;

@interface SBLockScreenSnoozedAlarmCell : SBLockScreenBulletinCell <SBDateLabelDelegate>
{
    SBSnoozedAlarmDateLabel *_countdownLabel;
}

+ (BOOL)wantsUnlockActionText;
+ (float)rowHeight;
- (void)dateLabelDidChange:(id)arg1;
- (void)setContentAlpha:(float)arg1;
- (void)setFireDate:(id)arg1;
- (void)layoutSubviews;
- (void)dealloc;

@end

