/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIScrollView.h"

#import "UIGestureRecognizerDelegate.h"

@class SBLockScreenNotificationCell;

@interface SBLockScreenNotificationScrollView : UIScrollView <UIGestureRecognizerDelegate>
{
    SBLockScreenNotificationCell *_associatedCell;
}

+ (float)scrollThresholdForPasscodeScroll;
@property(nonatomic) SBLockScreenNotificationCell *associatedCell; // @synthesize associatedCell=_associatedCell;

@end

