/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBLockScreenNotificationCell.h"

@interface SBLockScreenBulletinCell : SBLockScreenNotificationCell
{
}

+ (float)paddingBetweenTitleAndRelevanceDate;
+ (float)rowHeightForTitle:(id)arg1 subtitle:(id)arg2 body:(id)arg3 maxLines:(unsigned int)arg4 attachmentSize:(struct CGSize)arg5 datesVisible:(BOOL)arg6 rowWidth:(float)arg7 includeUnlockActionText:(BOOL)arg8;

@end

