/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBNotificationCell.h"

@class SBLockScreenNotificationScrollView, SBUnlockActionContext, UIButton, UILabel, UIView;

@interface SBLockScreenNotificationCell : SBNotificationCell
{
    BOOL _isTopCell;
    BOOL _drawsSeparators;
    float _currentContentAlpha;
    UIView *_topSeparatorView;
    UIView *_bottomSeparatorView;
    id <SBAwayListCellButtonHandler> _actionButtonHandler;
    SBLockScreenNotificationScrollView *_contentScrollView;
    SBUnlockActionContext *_unlockActionContext;
    UILabel *_unlockTextLabel;
    id <UIScrollViewDelegate> _delegate;
    BOOL _resetsScrollOnPluginWillDisable;
    float _contentScrollViewWidth;
}

+ (float)primaryPaddingLeft;
+ (BOOL)wantsUnlockActionText;
+ (float)rowHeightForTitle:(id)arg1 subtitle:(id)arg2 body:(id)arg3 maxLines:(unsigned int)arg4 attachmentSize:(struct CGSize)arg5 datesVisible:(BOOL)arg6 rowWidth:(float)arg7 includeUnlockActionText:(BOOL)arg8;
+ (id)defaultColorForEventDate;
+ (id)defaultColorForRelevanceDate;
+ (id)defaultColorForSecondaryText;
+ (id)defaultColorForSubtitleText;
+ (id)defaultColorForPrimaryText;
+ (id)defaultFontForEventDate;
+ (id)defaultFontForRelevanceDate;
+ (id)defaultFontForSecondaryText;
+ (id)defaultFontForSubtitleText;
+ (id)defaultFontForPrimaryText;
@property(nonatomic) BOOL resetsScrollOnPluginWillDisable; // @synthesize resetsScrollOnPluginWillDisable=_resetsScrollOnPluginWillDisable;
@property(nonatomic) id <UIScrollViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SBUnlockActionContext *unlockActionContext; // @synthesize unlockActionContext=_unlockActionContext;
@property(nonatomic) float contentScrollViewWidth; // @synthesize contentScrollViewWidth=_contentScrollViewWidth;
@property(nonatomic) BOOL drawsSeparators; // @synthesize drawsSeparators=_drawsSeparators;
@property(nonatomic) BOOL isTopCell; // @synthesize isTopCell=_isTopCell;
- (void)layoutSubviews;
- (void)_handleActionButtonPress:(id)arg1;
- (id)_buttonWithLabel:(id)arg1;
- (void)setButtonLabel:(id)arg1 handler:(id)arg2;
- (void)setRelevanceDateLabel:(id)arg1;
- (void)_updateUnlockText:(id)arg1;
- (void)_setSeparatorBackdropOverlayBlendMode:(int)arg1;
- (int)_separatorBackdropOverlayBlendMode;
- (id)_vibrantTextColor;
- (void)setContentAlpha:(float)arg1;
- (void)scrollToOriginAnimated:(BOOL)arg1;
- (void)resetScrollView;
- (void)_notePluginWillDisable:(id)arg1;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (id)_separatorColor;

// Remaining properties
@property(retain, nonatomic) UIButton *actionButton;

@end

