/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBStatusBarStateProvider.h"

#import "UIStatusBarStateObserver.h"

@interface SBMainStatusBarStateProvider : SBStatusBarStateProvider <UIStatusBarStateObserver>
{
    BOOL _overridePercent;
    BOOL _killActivity;
    char _itemIsDisabled[25];
    char _itemWasDisabled[25];
    BOOL _timeEnabled;
    BOOL _timeCloaked;
    BOOL _allButBatteryCloaked;
    BOOL _telephonyAndBluetoothCloaked;
}

+ (id)sharedInstance;
- (void)statusBarStateProvider:(id)arg1 didPostStatusBarData:(const CDStruct_4ec3be00 *)arg2 withActions:(int)arg3;
- (void)_composePostDataFromAggregatorData:(CDStruct_4ec3be00 *)arg1;
- (BOOL)_shouldPostForVisitedItem:(int)arg1 withUpdates:(BOOL)arg2 toAggregatorData:(const CDStruct_4ec3be00 *)arg3;
- (void)setTelephonyAndBluetoothItemsCloaked:(BOOL)arg1;
- (void)setAllItemsExceptBatteryCloaked:(BOOL)arg1;
- (void)setTimeCloaked:(BOOL)arg1;
- (void)enableTime:(BOOL)arg1 crossfade:(BOOL)arg2 crossfadeDuration:(double)arg3;
- (void)enableTime:(BOOL)arg1;
- (BOOL)isTimeEnabled;
- (void)_updateDisabledItems;
- (void)dealloc;
- (id)init;

@end

