/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray;

@interface SBModeControlManager : NSObject
{
    NSArray *_views;
}

+ (id)_segmentedControlForUse:(int)arg1 graphicsQuaility:(int)arg2;
+ (void)_configureSegmentedControlForLabelUse:(id)arg1;
+ (void)_configureSegmentedControlForButtonUse:(id)arg1;
+ (void)_configureSegmentedControl:(id)arg1 forGraphicsQuaility:(int)arg2;
@property(readonly, nonatomic) NSArray *views; // @synthesize views=_views;
- (void)setTintColor:(id)arg1 forUse:(int)arg2;
- (void)removeAllSegments;
- (void)insertSegmentWithTitle:(id)arg1 atIndex:(unsigned int)arg2 animated:(BOOL)arg3;
- (void)addTarget:(id)arg1 action:(SEL)arg2;
@property(nonatomic) int selectedSegmentIndex;
@property(readonly, nonatomic) unsigned int numberOfSegments;
- (id)_segmentedControlForUse:(int)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithGraphicsQuality:(int)arg1;

@end

