/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class ATConnection;

@interface SBModelessSyncController : NSObject
{
    BOOL _isAppSyncing;
    BOOL _isSyncing;
    int _syncRegistrationToken;
    int _iCloudRestoreToken;
    BOOL _restoringFromICloud;
    BOOL _isAutoSyncing;
    BOOL _isWirelessSyncing;
    ATConnection *_airTrafficConnection;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) BOOL isSyncing; // @synthesize isSyncing=_isSyncing;
@property(readonly, nonatomic) BOOL isAppSyncing; // @synthesize isAppSyncing=_isAppSyncing;
- (void)_endObservingICloudRestoreStatus;
- (void)_beginObservingICloudRestoreStatus;
- (void)_iCloudStatusChanged;
@property(readonly, nonatomic) BOOL isRestoringFromICloud;
- (void)_updateIconsForStateChange;
- (void)_setAppSyncState:(BOOL)arg1;
- (void)_appSyncStateChanged;
- (void)gotLowBatteryWarning;
- (void)endMonitoring;
- (void)beginMonitoring;
- (void)connectionWasInterrupted:(id)arg1;
- (void)connection:(id)arg1 updatedProgress:(id)arg2;
@property(readonly, nonatomic) BOOL isWirelessSyncing; // @synthesize isWirelessSyncing=_isWirelessSyncing;
@property(readonly, nonatomic) BOOL isAutoSyncing; // @synthesize isAutoSyncing=_isAutoSyncing;
- (void)setIsSyncing:(BOOL)arg1;
- (void)dealloc;
- (id)init;

@end

