/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBIconLabelImageParameters.h"

@class NSString, UIFont;

@interface SBMutableIconLabelImageParameters : SBIconLabelImageParameters
{
}

@property(nonatomic) int style; // @dynamic style;
@property(nonatomic) BOOL containsEmoji; // @dynamic containsEmoji;
@property(nonatomic) BOOL canEllipsize; // @dynamic canEllipsize;
@property(nonatomic) BOOL containsNonLatinLikeCharacters; // @dynamic containsNonLatinLikeCharacters;
@property(retain, nonatomic) UIFont *font; // @dynamic font;
@property(nonatomic) struct CGSize maxSize; // @dynamic maxSize;
@property(copy, nonatomic) NSString *text; // @dynamic text;
- (id)copy;

@end

