/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBUnlockActionContext.h"

@class NSString;

@interface SBMutableUnlockActionContext : SBUnlockActionContext
{
}


// Remaining properties
@property(nonatomic) BOOL canBypassPinLock;
@property(nonatomic) BOOL deactivateAwayController;
@property(retain, nonatomic) NSString *identifier;
@property(retain, nonatomic) NSString *lockLabel;
@property(nonatomic) BOOL requiresUnlock;
@property(retain, nonatomic) NSString *shortLockLabel;
@property(copy, nonatomic) id unlockAction;
@end

