/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class NSMutableArray, UIImageView;

@interface SBNewsstandBackgroundView : UIView
{
    NSMutableArray *_shelfViews;
    UIImageView *_overlayGradientView;
    UIView *_bottomView;
}

+ (float)shelfHeightForOrientation:(int)arg1;
+ (float)baselineForShelfAtIndex:(unsigned int)arg1 withOrientation:(int)arg2;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

