/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBIconImageView.h"

@interface SBNewsstandItemIconImageView : SBIconImageView
{
}

+ (float)cornerRadius;
+ (int)_defaultIconFormat;
- (struct CGRect)visibleBounds;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)squareDarkeningOverlayImage;
- (id)darkeningOverlayImage;
- (id)_generateSquareContentsImage;
- (id)contentsImage;

@end

