/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "_SBFVibrantTableViewHeaderFooterView.h"

@class SBNotificationCenterSeparatorView, SBNotificationsClearButton, UIImageView, UILabel;

@interface SBNotificationsSectionHeaderView : _SBFVibrantTableViewHeaderFooterView
{
    UILabel *_titleLabel;
    UIImageView *_iconImageView;
    SBNotificationsClearButton *_xButton;
    SBNotificationsClearButton *_clearButton;
    UIImageView *_buttonBackground;
    id _xAction;
    id _clearAction;
    float _widthWhenShowingClear;
    BOOL _showingClear;
    SBNotificationCenterSeparatorView *_separator;
}

+ (void)_compositingFilterForView:(id)arg1;
+ (id)defaultBackgroundColorForGraphicsQuality:(int)arg1;
- (void)buttonAction:(id)arg1;
- (void)layoutSubviews;
- (void)resetAnimated:(BOOL)arg1;
- (void)_setShowsClear:(BOOL)arg1 animated:(BOOL)arg2;
- (BOOL)isShowingClear;
- (struct CGRect)_buttonBackgroundFrame;
- (struct CGRect)_xButtonFrame;
- (struct CGRect)contentBounds;
- (void)setTarget:(id)arg1 forClearButtonAction:(id)arg2;
- (void)setTarget:(id)arg1 forClearButtonVisibleAction:(id)arg2;
- (void)setHasClearButton:(BOOL)arg1;
- (id)_clearImage;
- (id)_clearBackgroundImage;
- (id)_xImage;
- (void)setFloating:(BOOL)arg1;
- (void)prepareForReuse;
- (void)setBackgroundView:(id)arg1;
- (int)initialGraphicsQuality;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

