/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBBBBulletinInfo.h"

@class SBNotificationsSectionInfo, UIColor, UIImage;

@interface SBNotificationsBulletinInfo : SBBBBulletinInfo
{
    SBNotificationsSectionInfo *_sectionInfo;
    float _heightForReusableView;
    struct CGSize _referenceSize;
    UIImage *_icon;
    UIImage *_attachmentImage;
    struct CGSize _attachmentImageSize;
    float _secondaryTextHeight;
    BOOL _suppressingMessageForPrivacy;
    BOOL _isCachedMessageSuppressionValid;
    UIColor *_secondaryTextColor;
}

@property(readonly, nonatomic) UIColor *secondaryTextColor; // @synthesize secondaryTextColor=_secondaryTextColor;
@property(retain, nonatomic) SBNotificationsSectionInfo *sectionInfo; // @synthesize sectionInfo=_sectionInfo;
@property(nonatomic) struct CGSize attachmentImageSize; // @synthesize attachmentImageSize=_attachmentImageSize;
@property(retain, nonatomic) UIImage *attachmentImage; // @synthesize attachmentImage=_attachmentImage;
@property(retain, nonatomic) UIImage *icon; // @synthesize icon=_icon;
- (void)populateReusableView:(id)arg1;
- (float)heightForReusableViewInTableView:(id)arg1;
- (BOOL)_isLayoutValidWithReferenceSize:(struct CGSize)arg1;
- (struct CGSize)_effectiveAttachmentImageSize;
- (id)_attachmentImageToDisplay;
- (id)_eventDateLabelForDisplay;
- (id)_eventDateLabel;
- (void)_configureEventDateLabel:(id)arg1;
- (id)_relevanceDateLabel;
- (void)_configureRelevanceDateLabel:(id)arg1;
- (CDStruct_89ddc8e1)_relevanceDateLabelDescription;
- (id)_endDate;
- (id)_secondaryTextColor;
- (id)_secondaryTextToDisplay;
- (id)_secondaryText;
- (id)_subtitleTextColor;
- (id)_subtitleTextToDisplay;
- (id)_subtitleText;
- (id)_relevanceDateTextColor;
- (id)_primaryTextColor;
@property(readonly, nonatomic, getter=isSuppressingMessageForPrivacy) BOOL suppressingMessageForPrivacy; // @synthesize suppressingMessageForPrivacy=_suppressingMessageForPrivacy;
- (id)_primaryText;
- (void)invalidateCachedLayoutData;
- (Class)reusableViewClass;
- (id)identifier;
- (void)dealloc;

@end

