/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@interface SBNotificationCenterSeparatorView : UIView
{
    float _height;
}

+ (id)separatorForCurrentState;
+ (int)_separatorViewModeForCurrentState;
+ (id)separatorWithScreenScale:(float)arg1 mode:(int)arg2;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)updateForCurrentState;
- (id)initWithFrame:(struct CGRect)arg1 mode:(int)arg2;

@end

