/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBAlertView.h"

#import "SBPowerDownViewInterface.h"
#import "UIGestureRecognizerDelegate.h"

@class NSTimer, SBFGlintyStringView, SBFakeStatusBarView, SBShapeView, UILabel, UILongPressGestureRecognizer, UIPanGestureRecognizer, UIView, _UIBackdropView;

@interface SBPowerDownView : SBAlertView <SBPowerDownViewInterface, UIGestureRecognizerDelegate>
{
    NSTimer *_autoDismissTimer;
    id <SBPowerDownViewDelegate> _delegate;
    SBFakeStatusBarView *_fakeStatusBarView;
    SBShapeView *_darkeningOutsideBarsUnderlay;
    SBShapeView *_darkeningInsideBarsUnderlay;
    UIView *_topContainer;
    UIView *_topBar;
    SBFGlintyStringView *_topBarLabel;
    UIView *_topBarLabelBackgroundView;
    _UIBackdropView *_topBarBackground;
    UIView *_bottomContainer;
    UIView *_bottomBar;
    UILabel *_bottomBarLabel;
    _UIBackdropView *_bottomBarBackground;
    BOOL _addedFakeStatusBar;
    BOOL _hiddenLockScreenForeground;
    UIPanGestureRecognizer *_slideGestureRecognizer;
    UILongPressGestureRecognizer *_touchGestureRecognizer;
    struct CGPoint _slideGestureInitialPoint;
}

@property(nonatomic) id <SBPowerDownViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)_insideBarsPath;
- (id)_outsideBarsPath;
- (void)_animatePowerDown;
- (void)_slideCompleted:(BOOL)arg1;
- (void)_notifyDelegateCancelled;
- (void)_notifyDelegatePowerDown;
- (void)_resetAutoDismissTimer;
- (void)_cancelAutoDismissTimer;
- (id)_newDarkeningShapeView:(struct CGRect)arg1;
- (void)_removeFakeStatusBarIfNecessary;
- (void)_addFakeStatusBarIfNecessary;
- (id)_lockScreenView;
- (float)_bottomBarOffset;
- (float)_topBarOffset;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)_touchGestureRecognizer:(id)arg1;
- (void)_slideGestureRecognizer:(id)arg1;
- (void)layoutForInterfaceOrientation:(int)arg1;
- (BOOL)isSupportedInterfaceOrientation:(int)arg1;
- (void)animateOut;
- (void)animateIn;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

