/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "APSConnectionDelegate.h"

@class NSMutableDictionary, NSMutableSet, NSString;

@interface SBRemoteNotificationServer : NSObject <APSConnectionDelegate>
{
    NSMutableDictionary *_bundleIdentifiersToClients;
    NSMutableDictionary *_environmentsToConnections;
    NSMutableSet *_bundleIdentifiersNeedingToken;
    NSString *_lastNotificationReceivedBundleIdentifier;
    NSMutableDictionary *_appImportanceTracker;
}

+ (id)sharedInstance;
- (id)_allPushRegisteredThirdPartyBundleIDs;
- (void)clearMessageUserInfoForToken:(int)arg1 forBundleIdentifier:(id)arg2;
- (id)getMessageUserInfoForToken:(int)arg1 forBundleIdentifier:(id)arg2;
- (id)getMessageUserInfoForBundleIdentifier:(id)arg1;
- (void)setMessageUserInfo:(id)arg1 forToken:(int)arg2 forBundleIdentifier:(id)arg3;
- (void)setMessageUserInfo:(id)arg1 forBundleIdentifier:(id)arg2;
- (void)postSettingsChangedNotificationForBundleIdentifier:(id)arg1;
- (void)setSettingsTypes:(unsigned int)arg1 forBundleIdentifier:(id)arg2;
- (unsigned int)settingsEnabledTypesForBundleIdentifier:(id)arg1;
- (unsigned int)appEnabledTypesForBundleIdentifier:(id)arg1;
- (void)notePermissionAlertAcceptedTypes:(unsigned int)arg1 forBundleIdentifier:(id)arg2;
- (BOOL)hasRegisteredBundleIdentifiers;
- (void)setSystemwideEnabled:(BOOL)arg1;
- (BOOL)isSystemwideEnabled;
- (unsigned int)getEffectiveEnabledTypesForApplication:(id)arg1;
- (void)unregisterApplication:(id)arg1;
- (void)registerApplication:(id)arg1 forEnvironment:(id)arg2 withTypes:(unsigned int)arg3;
- (id)_allTopicsForApplication:(id)arg1;
- (id)_cloudDatabaseTopicsForApplication:(id)arg1;
- (void)calculateTopics;
- (void)_appDebugStateDidChange:(id)arg1;
- (void)_appStateDidChange:(id)arg1;
- (void)_appImportanceDecreased:(id)arg1;
- (void)_appImportanceIncreased:(id)arg1;
- (void)_moveTopicsForApp:(id)arg1 fromList:(unsigned int)arg2 toList:(unsigned int)arg3;
- (id)allSettingsEnabledTypeValues;
- (id)allAppEnabledTypeValues;
- (id)lastNotificationReceivedBundleIdentifier;
- (void)connection:(id)arg1 didReceiveIncomingMessage:(id)arg2;
- (void)connection:(id)arg1 didReceivePublicToken:(id)arg2;
- (void)connection:(id)arg1 didReceiveToken:(id)arg2 forTopic:(id)arg3 identifier:(id)arg4;
- (void)run;
- (void)dealloc;
- (id)init;

@end

