/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBIconZoomAnimator.h"

@class SBIcon, SBIconView, SBScaleZoomSettings, UIView;

@interface SBScaleIconZoomAnimator : SBIconZoomAnimator
{
    struct UIEdgeInsets _iconScootch;
    float _dockStretch;
    struct SBIconCoordinate _dockListCenterCoordinate;
    struct SBIconCoordinate _mainListCenterCoordinate;
    float _naturalVisualAltitude;
    UIView *_scalingView;
    SBIcon *_targetIcon;
    float _zoomScale;
}

@property(readonly, nonatomic) float zoomScale; // @synthesize zoomScale=_zoomScale;
@property(readonly, nonatomic) SBIcon *targetIcon; // @synthesize targetIcon=_targetIcon;
- (void)_calculateIconScootch;
- (struct CGPoint)_scootchForIcon:(id)arg1 inDock:(BOOL)arg2;
- (void)_applyOuterFadeFraction:(float)arg1;
- (void)_applyZoomFraction:(float)arg1;
- (float)_zoomedVisualAltitude;
- (struct CGPoint)_zoomedIconCenter;
- (struct CGRect)_zoomedFrame;
- (void)_animateToFraction:(float)arg1 afterDelay:(double)arg2 withSharedCompletion:(id)arg3;
- (unsigned int)_numberOfSignificantAnimations;
- (void)_cleanupAnimation;
- (void)_setAnimationFraction:(float)arg1;
- (void)_prepareAnimation;
@property(readonly, nonatomic) SBIconView *targetIconView;
- (void)dealloc;
- (id)initWithFolderController:(id)arg1 targetIcon:(id)arg2;

// Remaining properties
@property(retain, nonatomic) SBScaleZoomSettings *settings;

@end

