/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class UIFont;

@interface SBSearchTableViewContentSizeCache : NSObject
{
    UIFont *_bodyFont;
    UIFont *_caption1Font;
    UIFont *_boldCaption1Font;
    UIFont *_footnoteFont;
    float _baseHeight;
    float _footnoteFontLineHeight;
    float _footnoteFontAscender;
    float _bodyFontLineHeight;
    float _bodyFontAscender;
    float _caption1FontLineHeight;
    float _caption1FontAscender;
    float _emphasizedCaption1FontLineHeight;
    float _emphasizedCaption1FontAscender;
    float _summaryLineHeight;
}

+ (id)sharedInstance;
@property(nonatomic) float summaryLineHeight; // @synthesize summaryLineHeight=_summaryLineHeight;
@property(nonatomic) float emphasizedCaption1FontAscender; // @synthesize emphasizedCaption1FontAscender=_emphasizedCaption1FontAscender;
@property(nonatomic) float emphasizedCaption1FontLineHeight; // @synthesize emphasizedCaption1FontLineHeight=_emphasizedCaption1FontLineHeight;
@property(nonatomic) float caption1FontAscender; // @synthesize caption1FontAscender=_caption1FontAscender;
@property(nonatomic) float caption1FontLineHeight; // @synthesize caption1FontLineHeight=_caption1FontLineHeight;
@property(nonatomic) float bodyFontAscender; // @synthesize bodyFontAscender=_bodyFontAscender;
@property(nonatomic) float bodyFontLineHeight; // @synthesize bodyFontLineHeight=_bodyFontLineHeight;
@property(nonatomic) float footnoteFontAscender; // @synthesize footnoteFontAscender=_footnoteFontAscender;
@property(nonatomic) float footnoteFontLineHeight; // @synthesize footnoteFontLineHeight=_footnoteFontLineHeight;
@property(nonatomic) float baseHeight; // @synthesize baseHeight=_baseHeight;
@property(retain, nonatomic) UIFont *footnoteFont; // @synthesize footnoteFont=_footnoteFont;
@property(retain, nonatomic) UIFont *boldCaption1Font; // @synthesize boldCaption1Font=_boldCaption1Font;
@property(retain, nonatomic) UIFont *caption1Font; // @synthesize caption1Font=_caption1Font;
@property(retain, nonatomic) UIFont *bodyFont; // @synthesize bodyFont=_bodyFont;
- (void)contentSizeDidChange;

@end

