/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "UIScrollViewDelegate.h"

@class NSHashTable, SBSearchScrollView, UIView;

@interface SBSearchGesture : NSObject <UIScrollViewDelegate>
{
    NSHashTable *_observers;
    SBSearchScrollView *_scrollView;
    BOOL _suppressObserverCallbacks;
    BOOL _animatingResetOrReveal;
    BOOL _enabled;
    UIView *_targetView;
}

+ (id)sharedInstance;
@property(nonatomic) BOOL enabled; // @synthesize enabled=_enabled;
@property(readonly, nonatomic, getter=isAnimatingResetOrReveal) BOOL animatingResetOrReveal; // @synthesize animatingResetOrReveal=_animatingResetOrReveal;
@property(retain, nonatomic) UIView *targetView; // @synthesize targetView=_targetView;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_displayLaunched:(id)arg1;
- (void)_openFolderChanged:(id)arg1;
- (void)_iconEditingStateChanged:(id)arg1;
- (void)_updateScrollingEnabled;
- (BOOL)_isShowingSearch;
- (void)_updateForFinalContentOffset;
- (void)_updateForScrollingEnded;
- (void)resetAnimated:(BOOL)arg1;
- (void)revealAnimated:(BOOL)arg1;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)updateForRotation;
- (void)dealloc;
- (id)init;

@end

