/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

#import "SBSearchGestureObserver.h"
#import "SBSearchHeaderDelegate.h"
#import "SPSearchAgentDelegate.h"
#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class SBSearchHeader, SBSearchResultsBackdropView, UIImage, UILabel, UIPanGestureRecognizer, UITableView, UITapGestureRecognizer, UIView;

@interface SBSearchViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, SPSearchAgentDelegate, SBSearchGestureObserver, UISearchBarDelegate, SBSearchHeaderDelegate>
{
    SBSearchHeader *_searchHeader;
    SBSearchResultsBackdropView *_tableBackdrop;
    UITableView *_tableView;
    UILabel *_noResultsLabel;
    UIView *_touchStealingView;
    UITapGestureRecognizer *_tapRecognizer;
    UIPanGestureRecognizer *_panRecognizer;
    void *_addressBook;
    UIImage *_placeHolderImages[15];
    float _lastContentOffsetY;
    BOOL _scrollDown;
    BOOL _hasShownBackgroundSinceLastClear;
    id _fadeOutCompletionBlock;
    BOOL _fadingOut;
    BOOL _visible;
}

+ (id)sharedInstance;
@property(readonly, nonatomic, getter=isVisible) BOOL visible; // @synthesize visible=_visible;
@property(readonly, nonatomic, getter=isFadingOut) BOOL fadingOut; // @synthesize fadingOut=_fadingOut;
- (void)cancelButtonPressed;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_searchFieldReturnPressed;
- (void)_searchFieldEditingChanged;
- (void)searchGesture:(id)arg1 completedShowing:(BOOL)arg2;
- (void)searchGesture:(id)arg1 changedPercentComplete:(float)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (BOOL)tableView:(id)arg1 wantsHeaderForSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didUnhighlightRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didHighlightRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)searchAgentClearedResults:(id)arg1;
- (void)searchAgentUpdatedResults:(id)arg1;
- (void)_resizeTableViewForPreferredContentSizeChange:(id)arg1;
- (void)_keyboardWillChangeFrame:(id)arg1;
- (void)_handlePanRecognizer:(id)arg1;
- (void)_handleTapRecognizer:(id)arg1;
- (void)_handleDismissGesture;
- (void)_fadeOutAndHideKeyboardIfNecessary:(id)arg1;
- (void)_fadeForLaunchWithDuration:(double)arg1 completion:(id)arg2;
- (void)_deselectTableViewCell;
- (void)_updateTableContents;
- (void)_startDownloadingAppForStoreIdentifier:(unsigned long long)arg1 bundleIdentifier:(id)arg2;
- (void)_populateCell:(id)arg1 atIndexPath:(id)arg2 inTableView:(id)arg3;
- (BOOL)_shouldDisplayImagesForDomain:(unsigned int)arg1;
- (id)_auxiliaryTitleForABRecordID:(int)arg1;
- (id)_placeHolderImageForDomain:(unsigned int)arg1;
- (BOOL)_hasNoResultsForQuery;
- (BOOL)_hasResults;
- (BOOL)_showingKeyboard;
- (void)_setShowingKeyboard:(BOOL)arg1;
- (void)dismiss;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (void)dealloc;
- (id)init;

@end

