/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@interface SBShapeView : UIView
{
}

+ (Class)layerClass;
- (id)_shapeLayer;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)setFillRule:(int)arg1;
- (void)setFillColor:(id)arg1;
- (void)setPath:(id)arg1;

@end

