/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBSIMLockEntryAlertView.h"

@class NSString;

@interface SBSIMLockPUKEntryAlertView : SBSIMLockEntryAlertView
{
    int _state;
    NSString *_enteredPUKCode;
    NSString *_newPIN;
}

- (void)_attemptPUKUnlock;
- (id)_pukAttemptsRemainingLabel;
- (void)_unlock;
- (void)setupFailureState;
- (void)setupSuccess;
- (id)label;
- (id)titleText;
- (void)dealloc;

@end

