/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@interface SBSizeObservingView : UIView
{
    BOOL _delegateInterestedInSizeChanges;
    id <SBSizeObservingViewDelegate> _delegate;
}

@property(nonatomic) id <SBSizeObservingViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)setFrame:(struct CGRect)arg1;
- (void)setBounds:(struct CGRect)arg1;

@end

