/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSDateFormatter, NSHashTable, NSString, NSTimer;

@interface SBStatusBarStateAggregator : NSObject
{
    unsigned int _coalescentBlockDepth;
    BOOL _hasPostedOnce;
    unsigned int _itemPostState[25];
    BOOL _nonItemDataChanged;
    CDStruct_4ec3be00 _data;
    int _actions;
    NSHashTable *_postObservers;
    BOOL _notifyingPostObservers;
    NSDateFormatter *_timeItemDateFormatter;
    NSTimer *_timeItemTimer;
    NSString *_timeItemTimeString;
    NSString *_operatorName;
    NSString *_serviceString;
    NSString *_serviceCrossfadeString;
    NSArray *_countryCodesShowingEmergencyOnlyStatus;
    BOOL _showsActivityIndicatorOnHomeScreen;
    int _activityIndicatorEverywhereCount;
    BOOL _showsActivityIndicatorForNewsstand;s
    int _syncActivityIndicatorCount;
    NSString *_activityDisplayIdentifier;
    BOOL _showingNotChargingItem;
    NSString *_batteryDetailString;
    BOOL _alarmEnabled;
    BOOL _applyingAssistantStyle;
}

+ (int)_thermalColorForLevel:(int)arg1;
+ (id)sharedInstance;
- (void)_noteNotChargingStatusChanged;
- (void)_setShowingNotChargingItem;
- (BOOL)_shouldShowNotChargingItem;
- (BOOL)_shouldShowEmergencyOnlyStatus;
- (id)_sbCarrierNameForOperator:(id)arg1;
- (id)_displayStringForRegistrationStatus:(int)arg1;
- (id)_displayStringForSIMStatus:(id)arg1;
- (BOOL)_simStatusMeansLocked:(id)arg1;
- (void)_noteAirplaneModeChanged;
- (void)_resetTimeItemFormatter;
- (void)_restartTimeItemTimer;
- (void)_stopTimeItemTimer;
- (void)_requestActions:(int)arg1;
- (void)_notifyNonItemDataChanged;
- (void)_notifyItemChanged:(int)arg1;
- (BOOL)_setItem:(int)arg1 enabled:(BOOL)arg2;
- (void)_postItem:(int)arg1 withState:(unsigned int)arg2;
- (void)updateStatusBarItem:(int)arg1;
- (void)_updateTetheringState;
- (void)_updateThermalColorItem;
- (void)_updateAssistantItem;
- (void)_updateAirplayItem;
- (void)_updateQuietModeItem;
- (void)_updateRotationLockItem;
- (void)_updateLocationItem;
- (void)_updateActivityItem;
- (void)_updateCallForwardingItem;
- (void)_updateVPNItem;
- (void)_updateAlarmItem;
- (void)_updateTTYItem;
- (void)_updateBluetoothBatteryItem;
- (void)_updateBluetoothItem;
- (void)_updateBatteryItems;
- (void)_updateDataNetworkItem;
- (void)_updateServiceItem;
- (void)_updateSignalStrengthItem;
- (void)_updateAirplaneMode;
- (void)_updateTimeItems;
- (void)_registerForNotifications;
- (void)removePostingObserver:(id)arg1;
- (void)addPostingObserver:(id)arg1;
- (void)sendStatusBarActions:(int)arg1;
- (void)setShowsSyncActivityIndicator:(BOOL)arg1;
- (void)setShowsActivityIndicatorForNewsstand:(BOOL)arg1;
- (void)setShowsActivityIndicatorEverywhere:(BOOL)arg1;
- (void)setShowsActivityIndicatorOnHomeScreen:(BOOL)arg1;
- (void)setAlarmEnabled:(BOOL)arg1;
- (id)operatorName;
- (void)endCoalescentBlock;
- (void)beginCoalescentBlock;
- (void)dealloc;
- (id)init;

@end

