/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

#import "SBStarkLauncher.h"
#import "SBStarkTouchLauncherObserver.h"

@class SBStarkFakeIconOperationController, SBStarkIconListModel, SBStarkTouchLauncherViewController, UIButton;

@interface SBStarkLowTouchLauncherViewController : UIViewController <SBStarkTouchLauncherObserver, SBStarkLauncher>
{
    SBStarkTouchLauncherViewController *_touchLauncherViewController;
    UIButton *_leftScrollButton;
    UIButton *_rightScrollButton;
}

+ (float)desiredHeightForBounds:(struct CGRect)arg1;
- (void)touchLauncherDidScroll:(id)arg1;
- (void)touchLauncherDidChangeScrollButtonInsets:(id)arg1;
@property(nonatomic) id <SBStarkAutoHideControlBarDelegate> autoHideDelegate;
@property(retain, nonatomic) SBStarkFakeIconOperationController *fakeIconOperationController;
@property(readonly, nonatomic) BOOL obscuresControlBar;
@property(readonly, nonatomic) BOOL hidesAutomatically;
@property(readonly, nonatomic) SBStarkIconListModel *iconList;
@property(nonatomic) float height;
- (void)_scrollRight;
- (void)_scrollLeft;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

