/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class NSArray, UIImage, UIImageView;

@interface SBStarkIconImageView : UIView
{
    UIImageView *_imageView;
    UIImage *_image;
    float _brightness;
    unsigned int _outerStripes;
    unsigned int _innerStripes;
    BOOL _needsStripeUpdating;
    NSArray *_outerStripesViews;
    NSArray *_innerStripesViews;
    UIView *_brightnessView;
}

- (id)_viewsForEdges:(unsigned int)arg1 ofWidth:(float)arg2 inFrame:(struct CGRect)arg3 withBGColor:(id)arg4 outRect:(struct CGRect *)arg5;
- (void)_updateStripesIfNeeded;
- (void)layoutSubviews;
@property(nonatomic) unsigned int innerStripes;
@property(nonatomic) unsigned int outerStripes;
@property(nonatomic) float brightness;
@property(retain, nonatomic) UIImage *image;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

