/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBStatusBarStateProvider.h"

@interface SBStarkStatusBarStateProvider : SBStatusBarStateProvider
{
}

+ (BOOL)_itemIsIgnored:(int)arg1;
- (void)_composePostDataFromAggregatorData:(CDStruct_4ec3be00 *)arg1;
- (BOOL)_shouldPostForUpdatesToNonItemData:(const CDStruct_4ec3be00 *)arg1;
- (BOOL)_shouldPostForVisitedItem:(int)arg1 withUpdates:(BOOL)arg2 toAggregatorData:(const CDStruct_4ec3be00 *)arg3;

@end

