/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "_UIRemoteViewController.h"

#import "SBUIStarkHomeScreenBackgroundHostInterface.h"
#import "SBUIStarkHomeScreenBackgroundProviderInterface.h"

@class SBStarkBackgroundProvider;

@interface SBStarkBackgroundProviderRemoteViewController : _UIRemoteViewController <SBUIStarkHomeScreenBackgroundHostInterface, SBUIStarkHomeScreenBackgroundProviderInterface>
{
    SBStarkBackgroundProvider *_provider;
    id <SBStarkBackgroundProviderRemoteViewControllerDelegate> _delegate;
}

+ (id)serviceViewControllerInterface;
+ (id)exportedInterface;
@property(nonatomic) id <SBStarkBackgroundProviderRemoteViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SBStarkBackgroundProvider *provider; // @synthesize provider=_provider;
- (void)switchToState:(id)arg1 withAnimationName:(id)arg2;
- (void)setViewportFrame:(struct CGRect)arg1;
- (void)viewServiceDidTerminateWithError:(id)arg1;
- (void)dealloc;

@end

