/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBWorkspaceTransaction.h"

@class SBApplication;

@interface SBToAppWorkspaceTransaction : SBWorkspaceTransaction
{
    SBApplication *_toApp;
    BOOL _activateSuspended;
    double _watchdogExtension;
    BOOL _fromAssistant;
    BOOL _fromSwitcher;
    id _activationHandlerBlock;
}

@property(readonly, nonatomic) SBApplication *toApplication; // @synthesize toApplication=_toApp;
- (void)_commit;
- (void)_captureApplicationData;
- (BOOL)_shouldBeWatchdogged:(id *)arg1;
- (double)_watchdogInterval;
- (void)_fireAndClearActivationContinuationForActivationFailureIfNecessary;
- (void)_interruptWithReason:(int)arg1;
- (void)_transactionComplete;
- (void)activate:(id)arg1;
- (void)toggleStatusBarForCleanup;
- (void)performToAppStateCleanup;
- (BOOL)shouldAnimateOrientationChangeOnCompletion;
- (BOOL)shouldDismissSwitcher;
- (BOOL)shouldPerformToAppStateCleanupOnCompletion;
- (BOOL)shouldToggleSpringBoardStatusBarOnCleanup;
- (BOOL)shouldHideSpringBoardStatusBarOnCleanup;
- (id)debugDescription;
- (void)dealloc;
- (id)initWithWorkspace:(id)arg1 alertManager:(id)arg2 toApplication:(id)arg3 activationHandler:(id)arg4;

@end

