/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface SBTransientActiveInterfaceOrientationRequester : NSObject
{
    int _orientation;
    NSString *_reason;
}

@property(readonly, nonatomic) int orientation; // @synthesize orientation=_orientation;
@property(readonly, nonatomic) NSString *reason; // @synthesize reason=_reason;
- (void)dealloc;
- (id)initWithOrientation:(int)arg1 andReason:(id)arg2;

@end

