/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBUIAnimationFadeAlertToPhone.h"

@interface SBUIAnimationSnapAlertToPhone : SBUIAnimationFadeAlertToPhone
{
}

- (void)_cleanupAnimation;
- (BOOL)_shouldAnimateWallpaper;
- (void)_startAnimation;

@end

