/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBUIMainScreenAnimationController.h"

@class SBAlert, SBWindow, UIView, UIView<SBWindowContextAppearance>;

@interface SBUIAnimationAlertToPhoneBase : SBUIMainScreenAnimationController
{
    SBWindow *_transitionWindow;
    SBAlert *_deactivatingAlert;
    UIView<SBWindowContextAppearance> *_viewToAnimate;
    BOOL _reallyFinishedAnimating;
}

@property(retain, nonatomic, getter=_viewToAnimate, setter=_setViewToAnimate:) UIView *viewToAnimate; // @synthesize viewToAnimate=_viewToAnimate;
- (void)_maybeReportAnimationFinished;
- (BOOL)_isApplicationLaunchFinished;
- (void)_noteAnimationDidFinish;
- (void)_applicationDependencyStateChanged;
- (void)_cleanupAnimation;
- (void)_prepareAnimation;
- (id)_animationProgressDependency;
- (BOOL)_animationShouldStart;
- (void)_setHidden:(BOOL)arg1;
- (id)_getTransitionWindow;
- (void)_reallyFinishedAnimating;
- (BOOL)_shouldAnimateWallpaper;
- (id)_deactivatingAlert;
- (void)dealloc;
- (id)initWithAlert:(id)arg1 activatingApp:(id)arg2;

@end

