/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBUIMainScreenAnimationController.h"

@class SBAppStatusBarTransitionInfo, UIView;

@interface SBUIAnimationZoomUpApp : SBUIMainScreenAnimationController
{
    UIView *_contextHostView;
    BOOL _zoomHostView;
    SBAppStatusBarTransitionInfo *_appStatusBarTransitionInfo;
    int _animationTransition;
    BOOL _finishedZooming;
    BOOL _finishedActivating;
    BOOL _finishedCrossfadingToHostView;
    BOOL _animationFinished;
    BOOL _fromSwitcher;
    BOOL _fromNC;
    BOOL _fromCC;
    BOOL _fromAssistant;
    UIView *_viewToAnimate;
}

@property(nonatomic) int animationTransition; // @synthesize animationTransition=_animationTransition;
- (BOOL)_shouldWaitForSiriDismissBeforeZooming;
- (void)_maybeReportAnimationFinished;
- (void)_noteContextHostCrossfadeDidFinish;
- (void)_maybeStartCrossfade;
- (void)_noteZoomDidFinish;
- (void)_applicationDependencyStateChanged;
- (BOOL)isReasonableMomentToInterrupt;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (void)_prepareAnimation;
- (id)_animationProgressDependency;
- (BOOL)_animationShouldStart;
- (void)cleanupZoom;
- (void)animateZoomWithCompletion:(id)arg1;
- (void)prepareZoom;
- (void)noteDependencyDidInvalidate;
- (double)animationDelay;
- (double)animationDuration;
- (void)animateFakeStatusBarWithParameters:(id)arg1;
- (id)appStatusBarTransitionInfoWithStartStyleRequest:(id)arg1 startOrientation:(int)arg2;
- (void)dealloc;
- (id)initWithActivatingApp:(id)arg1;

@end

