/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBUIAnimationZoomUpApp.h"

#import "SBIconAnimatorDelegate.h"

@class SBIconAnimator;

@interface SBUIAnimationZoomUpAppFromHome : SBUIAnimationZoomUpApp <SBIconAnimatorDelegate>
{
    SBIconAnimator *_iconAnimator;
}

- (void)iconAnimatorWasInvalidated:(id)arg1;
- (void)cleanupZoom;
- (void)animateZoomWithCompletion:(id)arg1;
- (void)prepareZoom;
- (void)dealloc;

@end

