/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBUIMainScreenAnimationController.h"

@class SBLockScreenViewControllerBase, SBWindow, UIView, UIView<SBWindowContextAppearance>;

@interface SBUIAnimationPhoneToLockScreenBase : SBUIMainScreenAnimationController
{
    SBWindow *_transitionWindow;
    SBLockScreenViewControllerBase *_lockScreenViewController;
    UIView<SBWindowContextAppearance> *_contextHostView;
    BOOL _needsScreenDim;
}

@property(retain, nonatomic, getter=_contextHostView, setter=_setContextHostView:) UIView *contextHostView; // @synthesize contextHostView=_contextHostView;
- (void)_noteAnimationDidFinish;
- (void)_cleanupAnimation;
- (void)_prepareAnimation;
- (void)_setHidden:(BOOL)arg1;
- (BOOL)_shouldHideContextHostViewStatusBar;
- (id)_getTransitionWindow;
- (id)_lockScreenViewController;
- (void)dealloc;
- (id)initWithLockScreenController:(id)arg1 deactivatingApp:(id)arg2;

@end

