/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBAlertAdapter.h"

@interface SBUIFullscreenAlertAdapter : SBAlertAdapter
{
    BOOL _animatingDeactivation;
    BOOL _animatingActivation;
}

+ (id)_adapterForController:(id)arg1;
+ (void)alertAdapterDisplayDidDisappear:(id)arg1;
+ (void)deactivateAlertForController:(id)arg1 animated:(BOOL)arg2 animateOldDisplayInWithStyle:(int)arg3 isSlidingDisplay:(BOOL)arg4;
+ (void)activateAlertForController:(id)arg1 animated:(BOOL)arg2 animateCurrentDisplayOut:(BOOL)arg3 withDelay:(BOOL)arg4 isSlidingDisplay:(BOOL)arg5;
- (id)effectiveViewController;
- (void)setDisplay:(id)arg1;
- (void)deactivate;
- (void)activate;
- (void)setDisplaySetting:(unsigned int)arg1 flag:(BOOL)arg2;
- (void)handleAutoLock;
- (BOOL)handleHeadsetButtonPressed:(BOOL)arg1;
- (BOOL)handleVolumeDownButtonPressed;
- (BOOL)handleVolumeUpButtonPressed;
- (BOOL)handleLockButtonPressed;
- (BOOL)handleMenuButtonTap;
- (void)displayDidDisappear;
- (void)_updateForTransparentDismiss:(id)arg1;
- (void)_pluginViewDidAnimatedIn:(id)arg1;
- (void)animateViewIn;
- (void)prepareViewToAnimateIn;
- (BOOL)isCurrentlyAnimatingActivation;
- (void)setViewShouldAnimateIn:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)_pluginViewAnimatedOut:(id)arg1;
- (void)animateViewOut;
- (void)prepareViewToAnimateOut;
- (BOOL)currentlyAnimatingDeactivation;
- (BOOL)viewIsReadyToBeRemoved;
- (BOOL)_shouldDismissSwitcherOnActivation;
- (id)display;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;
- (BOOL)allowsStackingOfAlert:(id)arg1;
- (BOOL)hasTranslucentBackground;
- (BOOL)allowsEventOnlySuspension;
- (void)dealloc;
- (id)initWithAlertController:(id)arg1;

@end

