/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBUIAnimationZoomDownApp.h"

@interface SBUIAnimationZoomDownAppToPhone : SBUIAnimationZoomDownApp
{
    BOOL _usingSuperZoomImplementation;
    BOOL _fromPhoneAppToFaceTimeAppDuringCall;
}

- (void)_applicationDependencyStateChanged;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (void)_prepareAnimation;
- (void)animateZoomWithCompletion:(id)arg1;
- (BOOL)_shouldZoomUsingSuperImplementation;
- (id)_animationProgressDependency;
- (BOOL)_animationShouldStart;
- (void)dealloc;
- (void)_cleanupPhonesContextHostView;
- (id)appStatusBarTransitionInfoWithStartEffectivelyHidden:(BOOL)arg1 endStyleRequest:(id)arg2 endOrientation:(int)arg3;

@end

