/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class UIColor;

@protocol SBUIBannerView <NSObject>
- (id)bannerContext;

@optional
+ (id)defaultGrabberColor;
@property(copy, nonatomic) UIColor *grabberColor;
@end

