/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBUIMainScreenAnimationController.h"

@class SBLockScreenClippedSlideController, SBLockScreenViewControllerBase, UIView;

@interface SBUILockscreenSlideAnimationController : SBUIMainScreenAnimationController
{
    int _transitionStyle;
    SBLockScreenViewControllerBase *_lockscreenViewController;
    SBLockScreenClippedSlideController *_lockscreenClippedSlideController;
    UIView *_appView;
    double _animationDelay;
    double _animationDuration;
    BOOL _fromCC;
    BOOL _fromNC;
    BOOL _finishedSliding;
    BOOL _waitForAppActivationForContextHostView;
    BOOL _useContextHostView;
}

- (void)_maybeReportAnimationFinished;
- (void)_finishedSliding;
- (BOOL)_isApplicationLaunchFinished;
- (void)_applicationDependencyStateChanged;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (void)_prepareAnimation;
- (BOOL)_animationShouldStart;
- (id)_animationProgressDependency;
- (void)dealloc;
- (id)initWithActivatingApp:(id)arg1 deactivatingLockscreen:(id)arg2;
- (id)initWithActivatingLockscreen:(id)arg1 deactivatingApp:(id)arg2;
- (void)_setup:(id)arg1 transitionStyle:(int)arg2;
- (id)initWithActivatingApp:(id)arg1 deactivatingApp:(id)arg2;

@end

