/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "SBWallpaperObserver.h"
#import "_SBFakeBlurObserver.h"

@class UIColor, UIImage, UIImageView, UIView<_SBFakeBlur>;

@interface SBWallpaperEffectView : UIView <_SBFakeBlurObserver, SBWallpaperObserver>
{
    int _variant;
    UIColor *_wallpaperAverageColor;
    int _startStyle;
    int _endStyle;
    float _transitionFraction;
    UIView<_SBFakeBlur> *_blurView;
    UIView *_grayscaleTintView;
    UIView *_colorTintView;
    UIView<_SBFakeBlur> *_transitionBlurView;
    UIView *_transitionGrayscaleTintView;
    UIView *_transitionColorTintView;
    UIImageView *_maskImageView;
    UIView *_blurMaskingContainer;
    UIView *_tintMaskingContainer;
    UIImage *_maskImage;
    BOOL _shouldMaskBlur;
    BOOL _shouldMaskTint;
    BOOL _accessibilityIncreaseContrastEnabled;
}

+ (id)imageInRect:(struct CGRect)arg1 forVariant:(int)arg2 withStyle:(int)arg3 zoomFactor:(float)arg4 mask:(id)arg5 masksBlur:(BOOL)arg6 masksTint:(BOOL)arg7;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)_accessibilityEnhanceBackgroundContrastChanged:(id)arg1;
- (void)_clearView:(id *)arg1;
- (void)_configureGrayscaleTintView:(id *)arg1 colorTintView:(id *)arg2 forStyle:(int)arg3;
- (void)_configureViews;
- (void)_configureForCurrentBlurStyle;
- (void)_configureFromScratch;
- (void)_setTransitionFraction:(float)arg1;
- (void)_updateWallpaperAverageColor:(id)arg1;
- (void)wallpaperDidChangeForVariant:(int)arg1;
- (void)wallpaperLegibilitySettingsDidChange:(id)arg1 forVariant:(int)arg2;
- (void)fakeBlurView:(id)arg1 didChangeStyle:(int)arg2;
- (void)layoutSubviews;
- (void)setMaskImage:(id)arg1 masksBlur:(BOOL)arg2 masksTint:(BOOL)arg3;
- (BOOL)currentTransitionStateIsOpaque;
- (void)setTransitionState:(CDStruct_04b3617e)arg1;
- (BOOL)prepareToAnimateToTransitionState:(inout CDStruct_04b3617e *)arg1;
- (void)setStyle:(int)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithWallpaperVariant:(int)arg1;

@end

