/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol SBWallpaperObserver <NSObject>

@optional
- (void)wallpaperGeometryDidChangeForVariant:(int)arg1;
- (void)wallpaperLegibilitySettingsDidChange:(id)arg1 forVariant:(int)arg2;
- (void)wallpaperDidChangeForVariant:(int)arg1;
- (void)wallpaperWillChangeForVariant:(int)arg1;
@end

