/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UITableViewCell.h"

@class SBBBWidgetBulletinInfo;

@interface SBWidgetBulletinCell : UITableViewCell
{
    SBBBWidgetBulletinInfo *_representedWidgetBulletinInfo;
}

@property(retain, nonatomic) SBBBWidgetBulletinInfo *representedWidgetBulletinInfo; // @synthesize representedWidgetBulletinInfo=_representedWidgetBulletinInfo;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

