/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBFileLogger.h"

@interface SBWorkspaceLogger : SBFileLogger
{
}

+ (void)handleSignal;
+ (BOOL)saveRecentLogsToTemporaryPath:(id *)arg1;
+ (id)recentLogs;
+ (BOOL)isWorkspaceLoggingEnabled;
+ (int)workspaceLoggingType;
- (void)willBeginLoggingToPath:(id)arg1;
- (id)fileFormat:(id)arg1 withArguments:(void *)arg2;
- (BOOL)includeConsole;
- (void)reloadFromDefaults;
- (id)name;
- (BOOL)isEnabled;

@end

