/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@interface SBZoomView : UIView
{
}

+ (id)_chromeStatusBarImageForInterfaceOrientation:(int)arg1;
+ (struct CGSize)_rotateAndNormalizeSize:(struct CGSize)arg1 withTransform:(struct CGAffineTransform)arg2;
+ (int)_degreesForRotationFromOriginalImageOrientation:(int)arg1 toInterfaceOrientation:(int)arg2;
+ (int)_degreesForRotationFromInterfaceOrientation:(int)arg1 toInterfaceOrientation:(int)arg2;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (id)_initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

