/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol SFAirDropDiscoveryActionSheetDelegate <NSObject>

@optional
- (void)discoveryController:(id)arg1 actionSheetDidDismiss:(id)arg2;
- (void)discoveryController:(id)arg1 actionSheetWillDismiss:(id)arg2;
@end

