/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol SiriUISuggestionsViewDelegate <NSObject>

@optional
- (void)didShowSuggestionsForSuggestionsView:(id)arg1;
- (id)nextSuggestionsForSuggestionsView:(id)arg1 maxSuggestions:(unsigned int)arg2;
@end

