/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol SUNetworkObserver <NSObject>

@optional
- (void)operatorBundleChanged;
- (void)carrierBundleChanged;
- (void)cellularRoamingStatusChanged:(BOOL)arg1;
- (void)networkChangedFromNetworkType:(int)arg1 toNetworkType:(int)arg2;
@end

