/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UILabel.h"

@interface UILabel (SBStringDrawing)
- (void)drawWithMetrics:(id)arg1 inContext:(struct CGContext *)arg2;
- (id)stringMetricsForFirstLineWidth:(float)arg1;
@end

