/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol UIStatusBarStateObserver <NSObject>
- (void)statusBarStateProvider:(id)arg1 didPostStatusBarData:(const CDStruct_4ec3be00 *)arg2 withActions:(int)arg3;
@end

