/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@interface UIView (SpringBoardAdditions)
- (void)sb_removeAllSubviews;
- (id)sb_snapshotImage;
- (void)sbs_printLayerHierarchy;
- (void)_printLayer:(id)arg1 level:(int)arg2;
- (BOOL)hasActiveKeyboardOnScreen;
@end

